storage:
  type: memory

web:
  port: 8080

ui:
  title: "Menuvo Status"
  header: "Menuvo Status"

endpoints:
  - name: API
    group: core
    url: https://api.menuvo.app/health
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok"
