storage:
  type: sqlite
  path: /data/gatus.db

web:
  port: 8080

ui:
  title: "Menuvo Status"
  header: "Menuvo Status"
  description: "Public endpoint health checks"

security:
  basic:
    username: ${GATUS_BASIC_USER}
    password-bcrypt-base64: ${GATUS_BASIC_PASS_BCRYPT_BASE64}

alerting:
  telegram:
    token: ${GATUS_TELEGRAM_TOKEN}
    id: ${GATUS_TELEGRAM_CHAT_ID}

endpoints:
  - name: menuvo-live
    group: public
    url: https://menuvo.app/live
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok"
    alerts:
      - type: telegram
        description: "menuvo.app/live is down"
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2

  - name: menuvo-health
    group: public
    url: https://menuvo.app/health
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok"
      - "[BODY].db == ok"
      - "[BODY].redis == ok"
    alerts:
      - type: telegram
        description: "menuvo.app/health is failing"
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2
