storage:
  type: sqlite
  path: /data/gatus.db

web:
  port: 8080

ui:
  title: "Menuvo Status"
  header: "Menuvo Status"
  description: "Public endpoint health checks"

alerting:
  telegram:
    token: ${GATUS_TELEGRAM_TOKEN}
    id: ${GATUS_TELEGRAM_CHAT_ID}

endpoints:
  - name: menuvo-live
    group: public
    url: https://menuvo.app/live
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok"
    alerts:
      - type: telegram
        description: "menuvo.app/live is down"
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2

  - name: menuvo-health
    group: public
    url: https://menuvo.app/health
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok"
      - "[BODY].db == ok"
      - "[BODY].redis == ok"
    alerts:
      - type: telegram
        description: "menuvo.app/health is failing"
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2

  # Internal monitoring (not on public status page)
  - name: caddy
    group: internal
    url: http://menuvo-caddy:2019/config/
    interval: 60s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
        description: "Caddy reverse proxy is down"
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2

  - name: worker-images
    group: internal
    url: http://menuvo-worker-images:3001/health
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok"
    alerts:
      - type: telegram
        description: "Image worker is down"
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2

  - name: worker-imports
    group: internal
    url: http://menuvo-worker-imports:3001/health
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok"
    alerts:
      - type: telegram
        description: "Menu import worker is down"
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2
