storage:
  type: sqlite
  path: /data/gatus.db

web:
  port: 8080

ui:
  title: "Menuvo Status"
  header: "Menuvo Status"
  description: "Service health monitoring for Menuvo platform"

alerting:
  telegram:
    token: ${GATUS_TELEGRAM_TOKEN}
    id: ${GATUS_TELEGRAM_CHAT_ID}

endpoints:
  # API Server (Hetzner VPS)
  - name: api-health
    group: api
    url: https://api.menuvo.app/health
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok"
      - "[BODY].db == ok"
    alerts:
      - type: telegram
        description: "API health check failing"
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2

  - name: api-live
    group: api
    url: https://api.menuvo.app/live
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == ok"
    alerts:
      - type: telegram
        description: "API is down"
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2

  # Shop (Cloudflare Pages)
  - name: shop
    group: frontend
    url: https://menuvo.app
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 3000"
    alerts:
      - type: telegram
        description: "Shop is down"
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2

  # Console (Cloudflare Pages)
  - name: console
    group: frontend
    url: https://console.menuvo.app
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 3000"
    alerts:
      - type: telegram
        description: "Console is down"
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2

  # Business/Landing (Cloudflare Pages)
  - name: business
    group: frontend
    url: https://business.menuvo.app
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 3000"
    alerts:
      - type: telegram
        description: "Business site is down"
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2

  # Coolify Dashboard
  - name: coolify
    group: internal
    url: https://coolify.menuvo.app
    interval: 60s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: telegram
        description: "Coolify dashboard is down"
        send-on-resolved: true
        failure-threshold: 3
        success-threshold: 2
