/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as PublicOnboardingRouteImport } from './routes/_public/onboarding'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppMenuRouteImport } from './routes/_app/menu'
import { Route as AppKitchenRouteImport } from './routes/_app/kitchen'
import { Route as AppStoresIndexRouteImport } from './routes/_app/stores/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppHelpIndexRouteImport } from './routes/_app/help/index'
import { Route as PublicLegalPrivacyRouteImport } from './routes/_public/legal/privacy'
import { Route as PublicLegalImpressumRouteImport } from './routes/_public/legal/impressum'
import { Route as AppStoresNewRouteImport } from './routes/_app/stores/new'
import { Route as AppStoresStoreIdRouteImport } from './routes/_app/stores/$storeId'
import { Route as AppSettingsPaymentsRouteImport } from './routes/_app/settings/payments'
import { Route as AppSettingsLanguageRouteImport } from './routes/_app/settings/language'
import { Route as AppSettingsAiRouteImport } from './routes/_app/settings/ai'
import { Route as PublicAuthMerchantLoginRouteImport } from './routes/_public/auth/merchant/login'
import { Route as AppStoresStoreIdSettingsRouteImport } from './routes/_app/stores/$storeId/settings'
import { Route as AppStoresStoreIdServicePointsRouteImport } from './routes/_app/stores/$storeId/service-points'
import { Route as AppStoresStoreIdMenuRouteImport } from './routes/_app/stores/$storeId/menu'
import { Route as AppStoresStoreIdSettingsIndexRouteImport } from './routes/_app/stores/$storeId/settings/index'
import { Route as AppStoresStoreIdServicePointsIndexRouteImport } from './routes/_app/stores/$storeId/service-points/index'
import { Route as AppStoresStoreIdOrdersIndexRouteImport } from './routes/_app/stores/$storeId/orders/index'
import { Route as AppStoresStoreIdMenuIndexRouteImport } from './routes/_app/stores/$storeId/menu/index'
import { Route as AppStoresStoreIdKitchenIndexRouteImport } from './routes/_app/stores/$storeId/kitchen/index'
import { Route as AppStoresStoreIdSettingsOrderTypesRouteImport } from './routes/_app/stores/$storeId/settings/order-types'
import { Route as AppStoresStoreIdSettingsHoursRouteImport } from './routes/_app/stores/$storeId/settings/hours'
import { Route as AppStoresStoreIdSettingsClosuresRouteImport } from './routes/_app/stores/$storeId/settings/closures'
import { Route as AppStoresStoreIdServicePointsNewRouteImport } from './routes/_app/stores/$storeId/service-points/new'
import { Route as AppStoresStoreIdServicePointsBatchRouteImport } from './routes/_app/stores/$storeId/service-points/batch'
import { Route as AppStoresStoreIdServicePointsServicePointIdRouteImport } from './routes/_app/stores/$storeId/service-points/$servicePointId'
import { Route as AppStoresStoreIdOrdersOrderIdRouteImport } from './routes/_app/stores/$storeId/orders/$orderId'
import { Route as AppStoresStoreIdMenuImportRouteImport } from './routes/_app/stores/$storeId/menu/import'
import { Route as AppStoresStoreIdMenuVatIndexRouteImport } from './routes/_app/stores/$storeId/menu/vat/index'
import { Route as AppStoresStoreIdMenuOptionsIndexRouteImport } from './routes/_app/stores/$storeId/menu/options/index'
import { Route as AppStoresStoreIdServicePointsServicePointIdQrRouteImport } from './routes/_app/stores/$storeId/service-points/$servicePointId/qr'
import { Route as AppStoresStoreIdMenuVatNewRouteImport } from './routes/_app/stores/$storeId/menu/vat/new'
import { Route as AppStoresStoreIdMenuVatVatGroupIdRouteImport } from './routes/_app/stores/$storeId/menu/vat/$vatGroupId'
import { Route as AppStoresStoreIdMenuOptionsNewRouteImport } from './routes/_app/stores/$storeId/menu/options/new'
import { Route as AppStoresStoreIdMenuOptionsOptionGroupIdRouteImport } from './routes/_app/stores/$storeId/menu/options/$optionGroupId'
import { Route as AppStoresStoreIdMenuCategoriesNewRouteImport } from './routes/_app/stores/$storeId/menu/categories/new'
import { Route as AppStoresStoreIdMenuCategoriesCategoryIdIndexRouteImport } from './routes/_app/stores/$storeId/menu/categories/$categoryId/index'
import { Route as AppStoresStoreIdMenuCategoriesCategoryIdEditRouteImport } from './routes/_app/stores/$storeId/menu/categories/$categoryId/edit'
import { Route as AppStoresStoreIdMenuCategoriesCategoryIdItemsNewRouteImport } from './routes/_app/stores/$storeId/menu/categories/$categoryId/items/new'
import { Route as AppStoresStoreIdMenuCategoriesCategoryIdItemsItemIdRouteImport } from './routes/_app/stores/$storeId/menu/categories/$categoryId/items/$itemId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PublicOnboardingRoute = PublicOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PublicRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppKitchenRoute = AppKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresIndexRoute = AppStoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppHelpIndexRoute = AppHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => AppRoute,
} as any)
const PublicLegalPrivacyRoute = PublicLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLegalImpressumRoute = PublicLegalImpressumRouteImport.update({
  id: '/legal/impressum',
  path: '/legal/impressum',
  getParentRoute: () => PublicRoute,
} as any)
const AppStoresNewRoute = AppStoresNewRouteImport.update({
  id: '/stores/new',
  path: '/stores/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresStoreIdRoute = AppStoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPaymentsRoute = AppSettingsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsLanguageRoute = AppSettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAiRoute = AppSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppSettingsRoute,
} as any)
const PublicAuthMerchantLoginRoute = PublicAuthMerchantLoginRouteImport.update({
  id: '/auth/merchant/login',
  path: '/auth/merchant/login',
  getParentRoute: () => PublicRoute,
} as any)
const AppStoresStoreIdSettingsRoute =
  AppStoresStoreIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppStoresStoreIdRoute,
  } as any)
const AppStoresStoreIdServicePointsRoute =
  AppStoresStoreIdServicePointsRouteImport.update({
    id: '/service-points',
    path: '/service-points',
    getParentRoute: () => AppStoresStoreIdRoute,
  } as any)
const AppStoresStoreIdMenuRoute = AppStoresStoreIdMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppStoresStoreIdRoute,
} as any)
const AppStoresStoreIdSettingsIndexRoute =
  AppStoresStoreIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppStoresStoreIdSettingsRoute,
  } as any)
const AppStoresStoreIdServicePointsIndexRoute =
  AppStoresStoreIdServicePointsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppStoresStoreIdServicePointsRoute,
  } as any)
const AppStoresStoreIdOrdersIndexRoute =
  AppStoresStoreIdOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AppStoresStoreIdRoute,
  } as any)
const AppStoresStoreIdMenuIndexRoute =
  AppStoresStoreIdMenuIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppStoresStoreIdMenuRoute,
  } as any)
const AppStoresStoreIdKitchenIndexRoute =
  AppStoresStoreIdKitchenIndexRouteImport.update({
    id: '/kitchen/',
    path: '/kitchen/',
    getParentRoute: () => AppStoresStoreIdRoute,
  } as any)
const AppStoresStoreIdSettingsOrderTypesRoute =
  AppStoresStoreIdSettingsOrderTypesRouteImport.update({
    id: '/order-types',
    path: '/order-types',
    getParentRoute: () => AppStoresStoreIdSettingsRoute,
  } as any)
const AppStoresStoreIdSettingsHoursRoute =
  AppStoresStoreIdSettingsHoursRouteImport.update({
    id: '/hours',
    path: '/hours',
    getParentRoute: () => AppStoresStoreIdSettingsRoute,
  } as any)
const AppStoresStoreIdSettingsClosuresRoute =
  AppStoresStoreIdSettingsClosuresRouteImport.update({
    id: '/closures',
    path: '/closures',
    getParentRoute: () => AppStoresStoreIdSettingsRoute,
  } as any)
const AppStoresStoreIdServicePointsNewRoute =
  AppStoresStoreIdServicePointsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppStoresStoreIdServicePointsRoute,
  } as any)
const AppStoresStoreIdServicePointsBatchRoute =
  AppStoresStoreIdServicePointsBatchRouteImport.update({
    id: '/batch',
    path: '/batch',
    getParentRoute: () => AppStoresStoreIdServicePointsRoute,
  } as any)
const AppStoresStoreIdServicePointsServicePointIdRoute =
  AppStoresStoreIdServicePointsServicePointIdRouteImport.update({
    id: '/$servicePointId',
    path: '/$servicePointId',
    getParentRoute: () => AppStoresStoreIdServicePointsRoute,
  } as any)
const AppStoresStoreIdOrdersOrderIdRoute =
  AppStoresStoreIdOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AppStoresStoreIdRoute,
  } as any)
const AppStoresStoreIdMenuImportRoute =
  AppStoresStoreIdMenuImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AppStoresStoreIdMenuRoute,
  } as any)
const AppStoresStoreIdMenuVatIndexRoute =
  AppStoresStoreIdMenuVatIndexRouteImport.update({
    id: '/vat/',
    path: '/vat/',
    getParentRoute: () => AppStoresStoreIdMenuRoute,
  } as any)
const AppStoresStoreIdMenuOptionsIndexRoute =
  AppStoresStoreIdMenuOptionsIndexRouteImport.update({
    id: '/options/',
    path: '/options/',
    getParentRoute: () => AppStoresStoreIdMenuRoute,
  } as any)
const AppStoresStoreIdServicePointsServicePointIdQrRoute =
  AppStoresStoreIdServicePointsServicePointIdQrRouteImport.update({
    id: '/qr',
    path: '/qr',
    getParentRoute: () => AppStoresStoreIdServicePointsServicePointIdRoute,
  } as any)
const AppStoresStoreIdMenuVatNewRoute =
  AppStoresStoreIdMenuVatNewRouteImport.update({
    id: '/vat/new',
    path: '/vat/new',
    getParentRoute: () => AppStoresStoreIdMenuRoute,
  } as any)
const AppStoresStoreIdMenuVatVatGroupIdRoute =
  AppStoresStoreIdMenuVatVatGroupIdRouteImport.update({
    id: '/vat/$vatGroupId',
    path: '/vat/$vatGroupId',
    getParentRoute: () => AppStoresStoreIdMenuRoute,
  } as any)
const AppStoresStoreIdMenuOptionsNewRoute =
  AppStoresStoreIdMenuOptionsNewRouteImport.update({
    id: '/options/new',
    path: '/options/new',
    getParentRoute: () => AppStoresStoreIdMenuRoute,
  } as any)
const AppStoresStoreIdMenuOptionsOptionGroupIdRoute =
  AppStoresStoreIdMenuOptionsOptionGroupIdRouteImport.update({
    id: '/options/$optionGroupId',
    path: '/options/$optionGroupId',
    getParentRoute: () => AppStoresStoreIdMenuRoute,
  } as any)
const AppStoresStoreIdMenuCategoriesNewRoute =
  AppStoresStoreIdMenuCategoriesNewRouteImport.update({
    id: '/categories/new',
    path: '/categories/new',
    getParentRoute: () => AppStoresStoreIdMenuRoute,
  } as any)
const AppStoresStoreIdMenuCategoriesCategoryIdIndexRoute =
  AppStoresStoreIdMenuCategoriesCategoryIdIndexRouteImport.update({
    id: '/categories/$categoryId/',
    path: '/categories/$categoryId/',
    getParentRoute: () => AppStoresStoreIdMenuRoute,
  } as any)
const AppStoresStoreIdMenuCategoriesCategoryIdEditRoute =
  AppStoresStoreIdMenuCategoriesCategoryIdEditRouteImport.update({
    id: '/categories/$categoryId/edit',
    path: '/categories/$categoryId/edit',
    getParentRoute: () => AppStoresStoreIdMenuRoute,
  } as any)
const AppStoresStoreIdMenuCategoriesCategoryIdItemsNewRoute =
  AppStoresStoreIdMenuCategoriesCategoryIdItemsNewRouteImport.update({
    id: '/categories/$categoryId/items/new',
    path: '/categories/$categoryId/items/new',
    getParentRoute: () => AppStoresStoreIdMenuRoute,
  } as any)
const AppStoresStoreIdMenuCategoriesCategoryIdItemsItemIdRoute =
  AppStoresStoreIdMenuCategoriesCategoryIdItemsItemIdRouteImport.update({
    id: '/categories/$categoryId/items/$itemId',
    path: '/categories/$categoryId/items/$itemId',
    getParentRoute: () => AppStoresStoreIdMenuRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/kitchen': typeof AppKitchenRoute
  '/menu': typeof AppMenuRoute
  '/orders': typeof AppOrdersRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/onboarding': typeof PublicOnboardingRoute
  '/': typeof AppIndexRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/language': typeof AppSettingsLanguageRoute
  '/settings/payments': typeof AppSettingsPaymentsRoute
  '/stores/$storeId': typeof AppStoresStoreIdRouteWithChildren
  '/stores/new': typeof AppStoresNewRoute
  '/legal/impressum': typeof PublicLegalImpressumRoute
  '/legal/privacy': typeof PublicLegalPrivacyRoute
  '/help': typeof AppHelpIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/stores': typeof AppStoresIndexRoute
  '/stores/$storeId/menu': typeof AppStoresStoreIdMenuRouteWithChildren
  '/stores/$storeId/service-points': typeof AppStoresStoreIdServicePointsRouteWithChildren
  '/stores/$storeId/settings': typeof AppStoresStoreIdSettingsRouteWithChildren
  '/auth/merchant/login': typeof PublicAuthMerchantLoginRoute
  '/stores/$storeId/menu/import': typeof AppStoresStoreIdMenuImportRoute
  '/stores/$storeId/orders/$orderId': typeof AppStoresStoreIdOrdersOrderIdRoute
  '/stores/$storeId/service-points/$servicePointId': typeof AppStoresStoreIdServicePointsServicePointIdRouteWithChildren
  '/stores/$storeId/service-points/batch': typeof AppStoresStoreIdServicePointsBatchRoute
  '/stores/$storeId/service-points/new': typeof AppStoresStoreIdServicePointsNewRoute
  '/stores/$storeId/settings/closures': typeof AppStoresStoreIdSettingsClosuresRoute
  '/stores/$storeId/settings/hours': typeof AppStoresStoreIdSettingsHoursRoute
  '/stores/$storeId/settings/order-types': typeof AppStoresStoreIdSettingsOrderTypesRoute
  '/stores/$storeId/kitchen': typeof AppStoresStoreIdKitchenIndexRoute
  '/stores/$storeId/menu/': typeof AppStoresStoreIdMenuIndexRoute
  '/stores/$storeId/orders': typeof AppStoresStoreIdOrdersIndexRoute
  '/stores/$storeId/service-points/': typeof AppStoresStoreIdServicePointsIndexRoute
  '/stores/$storeId/settings/': typeof AppStoresStoreIdSettingsIndexRoute
  '/stores/$storeId/menu/categories/new': typeof AppStoresStoreIdMenuCategoriesNewRoute
  '/stores/$storeId/menu/options/$optionGroupId': typeof AppStoresStoreIdMenuOptionsOptionGroupIdRoute
  '/stores/$storeId/menu/options/new': typeof AppStoresStoreIdMenuOptionsNewRoute
  '/stores/$storeId/menu/vat/$vatGroupId': typeof AppStoresStoreIdMenuVatVatGroupIdRoute
  '/stores/$storeId/menu/vat/new': typeof AppStoresStoreIdMenuVatNewRoute
  '/stores/$storeId/service-points/$servicePointId/qr': typeof AppStoresStoreIdServicePointsServicePointIdQrRoute
  '/stores/$storeId/menu/options': typeof AppStoresStoreIdMenuOptionsIndexRoute
  '/stores/$storeId/menu/vat': typeof AppStoresStoreIdMenuVatIndexRoute
  '/stores/$storeId/menu/categories/$categoryId/edit': typeof AppStoresStoreIdMenuCategoriesCategoryIdEditRoute
  '/stores/$storeId/menu/categories/$categoryId': typeof AppStoresStoreIdMenuCategoriesCategoryIdIndexRoute
  '/stores/$storeId/menu/categories/$categoryId/items/$itemId': typeof AppStoresStoreIdMenuCategoriesCategoryIdItemsItemIdRoute
  '/stores/$storeId/menu/categories/$categoryId/items/new': typeof AppStoresStoreIdMenuCategoriesCategoryIdItemsNewRoute
}
export interface FileRoutesByTo {
  '/kitchen': typeof AppKitchenRoute
  '/menu': typeof AppMenuRoute
  '/orders': typeof AppOrdersRoute
  '/onboarding': typeof PublicOnboardingRoute
  '/': typeof AppIndexRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/language': typeof AppSettingsLanguageRoute
  '/settings/payments': typeof AppSettingsPaymentsRoute
  '/stores/$storeId': typeof AppStoresStoreIdRouteWithChildren
  '/stores/new': typeof AppStoresNewRoute
  '/legal/impressum': typeof PublicLegalImpressumRoute
  '/legal/privacy': typeof PublicLegalPrivacyRoute
  '/help': typeof AppHelpIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/stores': typeof AppStoresIndexRoute
  '/auth/merchant/login': typeof PublicAuthMerchantLoginRoute
  '/stores/$storeId/menu/import': typeof AppStoresStoreIdMenuImportRoute
  '/stores/$storeId/orders/$orderId': typeof AppStoresStoreIdOrdersOrderIdRoute
  '/stores/$storeId/service-points/$servicePointId': typeof AppStoresStoreIdServicePointsServicePointIdRouteWithChildren
  '/stores/$storeId/service-points/batch': typeof AppStoresStoreIdServicePointsBatchRoute
  '/stores/$storeId/service-points/new': typeof AppStoresStoreIdServicePointsNewRoute
  '/stores/$storeId/settings/closures': typeof AppStoresStoreIdSettingsClosuresRoute
  '/stores/$storeId/settings/hours': typeof AppStoresStoreIdSettingsHoursRoute
  '/stores/$storeId/settings/order-types': typeof AppStoresStoreIdSettingsOrderTypesRoute
  '/stores/$storeId/kitchen': typeof AppStoresStoreIdKitchenIndexRoute
  '/stores/$storeId/menu': typeof AppStoresStoreIdMenuIndexRoute
  '/stores/$storeId/orders': typeof AppStoresStoreIdOrdersIndexRoute
  '/stores/$storeId/service-points': typeof AppStoresStoreIdServicePointsIndexRoute
  '/stores/$storeId/settings': typeof AppStoresStoreIdSettingsIndexRoute
  '/stores/$storeId/menu/categories/new': typeof AppStoresStoreIdMenuCategoriesNewRoute
  '/stores/$storeId/menu/options/$optionGroupId': typeof AppStoresStoreIdMenuOptionsOptionGroupIdRoute
  '/stores/$storeId/menu/options/new': typeof AppStoresStoreIdMenuOptionsNewRoute
  '/stores/$storeId/menu/vat/$vatGroupId': typeof AppStoresStoreIdMenuVatVatGroupIdRoute
  '/stores/$storeId/menu/vat/new': typeof AppStoresStoreIdMenuVatNewRoute
  '/stores/$storeId/service-points/$servicePointId/qr': typeof AppStoresStoreIdServicePointsServicePointIdQrRoute
  '/stores/$storeId/menu/options': typeof AppStoresStoreIdMenuOptionsIndexRoute
  '/stores/$storeId/menu/vat': typeof AppStoresStoreIdMenuVatIndexRoute
  '/stores/$storeId/menu/categories/$categoryId/edit': typeof AppStoresStoreIdMenuCategoriesCategoryIdEditRoute
  '/stores/$storeId/menu/categories/$categoryId': typeof AppStoresStoreIdMenuCategoriesCategoryIdIndexRoute
  '/stores/$storeId/menu/categories/$categoryId/items/$itemId': typeof AppStoresStoreIdMenuCategoriesCategoryIdItemsItemIdRoute
  '/stores/$storeId/menu/categories/$categoryId/items/new': typeof AppStoresStoreIdMenuCategoriesCategoryIdItemsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/kitchen': typeof AppKitchenRoute
  '/_app/menu': typeof AppMenuRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_public/onboarding': typeof PublicOnboardingRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/ai': typeof AppSettingsAiRoute
  '/_app/settings/language': typeof AppSettingsLanguageRoute
  '/_app/settings/payments': typeof AppSettingsPaymentsRoute
  '/_app/stores/$storeId': typeof AppStoresStoreIdRouteWithChildren
  '/_app/stores/new': typeof AppStoresNewRoute
  '/_public/legal/impressum': typeof PublicLegalImpressumRoute
  '/_public/legal/privacy': typeof PublicLegalPrivacyRoute
  '/_app/help/': typeof AppHelpIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/stores/': typeof AppStoresIndexRoute
  '/_app/stores/$storeId/menu': typeof AppStoresStoreIdMenuRouteWithChildren
  '/_app/stores/$storeId/service-points': typeof AppStoresStoreIdServicePointsRouteWithChildren
  '/_app/stores/$storeId/settings': typeof AppStoresStoreIdSettingsRouteWithChildren
  '/_public/auth/merchant/login': typeof PublicAuthMerchantLoginRoute
  '/_app/stores/$storeId/menu/import': typeof AppStoresStoreIdMenuImportRoute
  '/_app/stores/$storeId/orders/$orderId': typeof AppStoresStoreIdOrdersOrderIdRoute
  '/_app/stores/$storeId/service-points/$servicePointId': typeof AppStoresStoreIdServicePointsServicePointIdRouteWithChildren
  '/_app/stores/$storeId/service-points/batch': typeof AppStoresStoreIdServicePointsBatchRoute
  '/_app/stores/$storeId/service-points/new': typeof AppStoresStoreIdServicePointsNewRoute
  '/_app/stores/$storeId/settings/closures': typeof AppStoresStoreIdSettingsClosuresRoute
  '/_app/stores/$storeId/settings/hours': typeof AppStoresStoreIdSettingsHoursRoute
  '/_app/stores/$storeId/settings/order-types': typeof AppStoresStoreIdSettingsOrderTypesRoute
  '/_app/stores/$storeId/kitchen/': typeof AppStoresStoreIdKitchenIndexRoute
  '/_app/stores/$storeId/menu/': typeof AppStoresStoreIdMenuIndexRoute
  '/_app/stores/$storeId/orders/': typeof AppStoresStoreIdOrdersIndexRoute
  '/_app/stores/$storeId/service-points/': typeof AppStoresStoreIdServicePointsIndexRoute
  '/_app/stores/$storeId/settings/': typeof AppStoresStoreIdSettingsIndexRoute
  '/_app/stores/$storeId/menu/categories/new': typeof AppStoresStoreIdMenuCategoriesNewRoute
  '/_app/stores/$storeId/menu/options/$optionGroupId': typeof AppStoresStoreIdMenuOptionsOptionGroupIdRoute
  '/_app/stores/$storeId/menu/options/new': typeof AppStoresStoreIdMenuOptionsNewRoute
  '/_app/stores/$storeId/menu/vat/$vatGroupId': typeof AppStoresStoreIdMenuVatVatGroupIdRoute
  '/_app/stores/$storeId/menu/vat/new': typeof AppStoresStoreIdMenuVatNewRoute
  '/_app/stores/$storeId/service-points/$servicePointId/qr': typeof AppStoresStoreIdServicePointsServicePointIdQrRoute
  '/_app/stores/$storeId/menu/options/': typeof AppStoresStoreIdMenuOptionsIndexRoute
  '/_app/stores/$storeId/menu/vat/': typeof AppStoresStoreIdMenuVatIndexRoute
  '/_app/stores/$storeId/menu/categories/$categoryId/edit': typeof AppStoresStoreIdMenuCategoriesCategoryIdEditRoute
  '/_app/stores/$storeId/menu/categories/$categoryId/': typeof AppStoresStoreIdMenuCategoriesCategoryIdIndexRoute
  '/_app/stores/$storeId/menu/categories/$categoryId/items/$itemId': typeof AppStoresStoreIdMenuCategoriesCategoryIdItemsItemIdRoute
  '/_app/stores/$storeId/menu/categories/$categoryId/items/new': typeof AppStoresStoreIdMenuCategoriesCategoryIdItemsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/kitchen'
    | '/menu'
    | '/orders'
    | '/settings'
    | '/onboarding'
    | '/'
    | '/settings/ai'
    | '/settings/language'
    | '/settings/payments'
    | '/stores/$storeId'
    | '/stores/new'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/help'
    | '/settings/'
    | '/stores'
    | '/stores/$storeId/menu'
    | '/stores/$storeId/service-points'
    | '/stores/$storeId/settings'
    | '/auth/merchant/login'
    | '/stores/$storeId/menu/import'
    | '/stores/$storeId/orders/$orderId'
    | '/stores/$storeId/service-points/$servicePointId'
    | '/stores/$storeId/service-points/batch'
    | '/stores/$storeId/service-points/new'
    | '/stores/$storeId/settings/closures'
    | '/stores/$storeId/settings/hours'
    | '/stores/$storeId/settings/order-types'
    | '/stores/$storeId/kitchen'
    | '/stores/$storeId/menu/'
    | '/stores/$storeId/orders'
    | '/stores/$storeId/service-points/'
    | '/stores/$storeId/settings/'
    | '/stores/$storeId/menu/categories/new'
    | '/stores/$storeId/menu/options/$optionGroupId'
    | '/stores/$storeId/menu/options/new'
    | '/stores/$storeId/menu/vat/$vatGroupId'
    | '/stores/$storeId/menu/vat/new'
    | '/stores/$storeId/service-points/$servicePointId/qr'
    | '/stores/$storeId/menu/options'
    | '/stores/$storeId/menu/vat'
    | '/stores/$storeId/menu/categories/$categoryId/edit'
    | '/stores/$storeId/menu/categories/$categoryId'
    | '/stores/$storeId/menu/categories/$categoryId/items/$itemId'
    | '/stores/$storeId/menu/categories/$categoryId/items/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/kitchen'
    | '/menu'
    | '/orders'
    | '/onboarding'
    | '/'
    | '/settings/ai'
    | '/settings/language'
    | '/settings/payments'
    | '/stores/$storeId'
    | '/stores/new'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/help'
    | '/settings'
    | '/stores'
    | '/auth/merchant/login'
    | '/stores/$storeId/menu/import'
    | '/stores/$storeId/orders/$orderId'
    | '/stores/$storeId/service-points/$servicePointId'
    | '/stores/$storeId/service-points/batch'
    | '/stores/$storeId/service-points/new'
    | '/stores/$storeId/settings/closures'
    | '/stores/$storeId/settings/hours'
    | '/stores/$storeId/settings/order-types'
    | '/stores/$storeId/kitchen'
    | '/stores/$storeId/menu'
    | '/stores/$storeId/orders'
    | '/stores/$storeId/service-points'
    | '/stores/$storeId/settings'
    | '/stores/$storeId/menu/categories/new'
    | '/stores/$storeId/menu/options/$optionGroupId'
    | '/stores/$storeId/menu/options/new'
    | '/stores/$storeId/menu/vat/$vatGroupId'
    | '/stores/$storeId/menu/vat/new'
    | '/stores/$storeId/service-points/$servicePointId/qr'
    | '/stores/$storeId/menu/options'
    | '/stores/$storeId/menu/vat'
    | '/stores/$storeId/menu/categories/$categoryId/edit'
    | '/stores/$storeId/menu/categories/$categoryId'
    | '/stores/$storeId/menu/categories/$categoryId/items/$itemId'
    | '/stores/$storeId/menu/categories/$categoryId/items/new'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/kitchen'
    | '/_app/menu'
    | '/_app/orders'
    | '/_app/settings'
    | '/_public/onboarding'
    | '/_app/'
    | '/_app/settings/ai'
    | '/_app/settings/language'
    | '/_app/settings/payments'
    | '/_app/stores/$storeId'
    | '/_app/stores/new'
    | '/_public/legal/impressum'
    | '/_public/legal/privacy'
    | '/_app/help/'
    | '/_app/settings/'
    | '/_app/stores/'
    | '/_app/stores/$storeId/menu'
    | '/_app/stores/$storeId/service-points'
    | '/_app/stores/$storeId/settings'
    | '/_public/auth/merchant/login'
    | '/_app/stores/$storeId/menu/import'
    | '/_app/stores/$storeId/orders/$orderId'
    | '/_app/stores/$storeId/service-points/$servicePointId'
    | '/_app/stores/$storeId/service-points/batch'
    | '/_app/stores/$storeId/service-points/new'
    | '/_app/stores/$storeId/settings/closures'
    | '/_app/stores/$storeId/settings/hours'
    | '/_app/stores/$storeId/settings/order-types'
    | '/_app/stores/$storeId/kitchen/'
    | '/_app/stores/$storeId/menu/'
    | '/_app/stores/$storeId/orders/'
    | '/_app/stores/$storeId/service-points/'
    | '/_app/stores/$storeId/settings/'
    | '/_app/stores/$storeId/menu/categories/new'
    | '/_app/stores/$storeId/menu/options/$optionGroupId'
    | '/_app/stores/$storeId/menu/options/new'
    | '/_app/stores/$storeId/menu/vat/$vatGroupId'
    | '/_app/stores/$storeId/menu/vat/new'
    | '/_app/stores/$storeId/service-points/$servicePointId/qr'
    | '/_app/stores/$storeId/menu/options/'
    | '/_app/stores/$storeId/menu/vat/'
    | '/_app/stores/$storeId/menu/categories/$categoryId/edit'
    | '/_app/stores/$storeId/menu/categories/$categoryId/'
    | '/_app/stores/$storeId/menu/categories/$categoryId/items/$itemId'
    | '/_app/stores/$storeId/menu/categories/$categoryId/items/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/onboarding': {
      id: '/_public/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof PublicOnboardingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu': {
      id: '/_app/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kitchen': {
      id: '/_app/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AppKitchenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stores/': {
      id: '/_app/stores/'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AppStoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/help/': {
      id: '/_app/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/legal/privacy': {
      id: '/_public/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof PublicLegalPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/legal/impressum': {
      id: '/_public/legal/impressum'
      path: '/legal/impressum'
      fullPath: '/legal/impressum'
      preLoaderRoute: typeof PublicLegalImpressumRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/stores/new': {
      id: '/_app/stores/new'
      path: '/stores/new'
      fullPath: '/stores/new'
      preLoaderRoute: typeof AppStoresNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stores/$storeId': {
      id: '/_app/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof AppStoresStoreIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/payments': {
      id: '/_app/settings/payments'
      path: '/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof AppSettingsPaymentsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/language': {
      id: '/_app/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof AppSettingsLanguageRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/ai': {
      id: '/_app/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AppSettingsAiRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_public/auth/merchant/login': {
      id: '/_public/auth/merchant/login'
      path: '/auth/merchant/login'
      fullPath: '/auth/merchant/login'
      preLoaderRoute: typeof PublicAuthMerchantLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/stores/$storeId/settings': {
      id: '/_app/stores/$storeId/settings'
      path: '/settings'
      fullPath: '/stores/$storeId/settings'
      preLoaderRoute: typeof AppStoresStoreIdSettingsRouteImport
      parentRoute: typeof AppStoresStoreIdRoute
    }
    '/_app/stores/$storeId/service-points': {
      id: '/_app/stores/$storeId/service-points'
      path: '/service-points'
      fullPath: '/stores/$storeId/service-points'
      preLoaderRoute: typeof AppStoresStoreIdServicePointsRouteImport
      parentRoute: typeof AppStoresStoreIdRoute
    }
    '/_app/stores/$storeId/menu': {
      id: '/_app/stores/$storeId/menu'
      path: '/menu'
      fullPath: '/stores/$storeId/menu'
      preLoaderRoute: typeof AppStoresStoreIdMenuRouteImport
      parentRoute: typeof AppStoresStoreIdRoute
    }
    '/_app/stores/$storeId/settings/': {
      id: '/_app/stores/$storeId/settings/'
      path: '/'
      fullPath: '/stores/$storeId/settings/'
      preLoaderRoute: typeof AppStoresStoreIdSettingsIndexRouteImport
      parentRoute: typeof AppStoresStoreIdSettingsRoute
    }
    '/_app/stores/$storeId/service-points/': {
      id: '/_app/stores/$storeId/service-points/'
      path: '/'
      fullPath: '/stores/$storeId/service-points/'
      preLoaderRoute: typeof AppStoresStoreIdServicePointsIndexRouteImport
      parentRoute: typeof AppStoresStoreIdServicePointsRoute
    }
    '/_app/stores/$storeId/orders/': {
      id: '/_app/stores/$storeId/orders/'
      path: '/orders'
      fullPath: '/stores/$storeId/orders'
      preLoaderRoute: typeof AppStoresStoreIdOrdersIndexRouteImport
      parentRoute: typeof AppStoresStoreIdRoute
    }
    '/_app/stores/$storeId/menu/': {
      id: '/_app/stores/$storeId/menu/'
      path: '/'
      fullPath: '/stores/$storeId/menu/'
      preLoaderRoute: typeof AppStoresStoreIdMenuIndexRouteImport
      parentRoute: typeof AppStoresStoreIdMenuRoute
    }
    '/_app/stores/$storeId/kitchen/': {
      id: '/_app/stores/$storeId/kitchen/'
      path: '/kitchen'
      fullPath: '/stores/$storeId/kitchen'
      preLoaderRoute: typeof AppStoresStoreIdKitchenIndexRouteImport
      parentRoute: typeof AppStoresStoreIdRoute
    }
    '/_app/stores/$storeId/settings/order-types': {
      id: '/_app/stores/$storeId/settings/order-types'
      path: '/order-types'
      fullPath: '/stores/$storeId/settings/order-types'
      preLoaderRoute: typeof AppStoresStoreIdSettingsOrderTypesRouteImport
      parentRoute: typeof AppStoresStoreIdSettingsRoute
    }
    '/_app/stores/$storeId/settings/hours': {
      id: '/_app/stores/$storeId/settings/hours'
      path: '/hours'
      fullPath: '/stores/$storeId/settings/hours'
      preLoaderRoute: typeof AppStoresStoreIdSettingsHoursRouteImport
      parentRoute: typeof AppStoresStoreIdSettingsRoute
    }
    '/_app/stores/$storeId/settings/closures': {
      id: '/_app/stores/$storeId/settings/closures'
      path: '/closures'
      fullPath: '/stores/$storeId/settings/closures'
      preLoaderRoute: typeof AppStoresStoreIdSettingsClosuresRouteImport
      parentRoute: typeof AppStoresStoreIdSettingsRoute
    }
    '/_app/stores/$storeId/service-points/new': {
      id: '/_app/stores/$storeId/service-points/new'
      path: '/new'
      fullPath: '/stores/$storeId/service-points/new'
      preLoaderRoute: typeof AppStoresStoreIdServicePointsNewRouteImport
      parentRoute: typeof AppStoresStoreIdServicePointsRoute
    }
    '/_app/stores/$storeId/service-points/batch': {
      id: '/_app/stores/$storeId/service-points/batch'
      path: '/batch'
      fullPath: '/stores/$storeId/service-points/batch'
      preLoaderRoute: typeof AppStoresStoreIdServicePointsBatchRouteImport
      parentRoute: typeof AppStoresStoreIdServicePointsRoute
    }
    '/_app/stores/$storeId/service-points/$servicePointId': {
      id: '/_app/stores/$storeId/service-points/$servicePointId'
      path: '/$servicePointId'
      fullPath: '/stores/$storeId/service-points/$servicePointId'
      preLoaderRoute: typeof AppStoresStoreIdServicePointsServicePointIdRouteImport
      parentRoute: typeof AppStoresStoreIdServicePointsRoute
    }
    '/_app/stores/$storeId/orders/$orderId': {
      id: '/_app/stores/$storeId/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/stores/$storeId/orders/$orderId'
      preLoaderRoute: typeof AppStoresStoreIdOrdersOrderIdRouteImport
      parentRoute: typeof AppStoresStoreIdRoute
    }
    '/_app/stores/$storeId/menu/import': {
      id: '/_app/stores/$storeId/menu/import'
      path: '/import'
      fullPath: '/stores/$storeId/menu/import'
      preLoaderRoute: typeof AppStoresStoreIdMenuImportRouteImport
      parentRoute: typeof AppStoresStoreIdMenuRoute
    }
    '/_app/stores/$storeId/menu/vat/': {
      id: '/_app/stores/$storeId/menu/vat/'
      path: '/vat'
      fullPath: '/stores/$storeId/menu/vat'
      preLoaderRoute: typeof AppStoresStoreIdMenuVatIndexRouteImport
      parentRoute: typeof AppStoresStoreIdMenuRoute
    }
    '/_app/stores/$storeId/menu/options/': {
      id: '/_app/stores/$storeId/menu/options/'
      path: '/options'
      fullPath: '/stores/$storeId/menu/options'
      preLoaderRoute: typeof AppStoresStoreIdMenuOptionsIndexRouteImport
      parentRoute: typeof AppStoresStoreIdMenuRoute
    }
    '/_app/stores/$storeId/service-points/$servicePointId/qr': {
      id: '/_app/stores/$storeId/service-points/$servicePointId/qr'
      path: '/qr'
      fullPath: '/stores/$storeId/service-points/$servicePointId/qr'
      preLoaderRoute: typeof AppStoresStoreIdServicePointsServicePointIdQrRouteImport
      parentRoute: typeof AppStoresStoreIdServicePointsServicePointIdRoute
    }
    '/_app/stores/$storeId/menu/vat/new': {
      id: '/_app/stores/$storeId/menu/vat/new'
      path: '/vat/new'
      fullPath: '/stores/$storeId/menu/vat/new'
      preLoaderRoute: typeof AppStoresStoreIdMenuVatNewRouteImport
      parentRoute: typeof AppStoresStoreIdMenuRoute
    }
    '/_app/stores/$storeId/menu/vat/$vatGroupId': {
      id: '/_app/stores/$storeId/menu/vat/$vatGroupId'
      path: '/vat/$vatGroupId'
      fullPath: '/stores/$storeId/menu/vat/$vatGroupId'
      preLoaderRoute: typeof AppStoresStoreIdMenuVatVatGroupIdRouteImport
      parentRoute: typeof AppStoresStoreIdMenuRoute
    }
    '/_app/stores/$storeId/menu/options/new': {
      id: '/_app/stores/$storeId/menu/options/new'
      path: '/options/new'
      fullPath: '/stores/$storeId/menu/options/new'
      preLoaderRoute: typeof AppStoresStoreIdMenuOptionsNewRouteImport
      parentRoute: typeof AppStoresStoreIdMenuRoute
    }
    '/_app/stores/$storeId/menu/options/$optionGroupId': {
      id: '/_app/stores/$storeId/menu/options/$optionGroupId'
      path: '/options/$optionGroupId'
      fullPath: '/stores/$storeId/menu/options/$optionGroupId'
      preLoaderRoute: typeof AppStoresStoreIdMenuOptionsOptionGroupIdRouteImport
      parentRoute: typeof AppStoresStoreIdMenuRoute
    }
    '/_app/stores/$storeId/menu/categories/new': {
      id: '/_app/stores/$storeId/menu/categories/new'
      path: '/categories/new'
      fullPath: '/stores/$storeId/menu/categories/new'
      preLoaderRoute: typeof AppStoresStoreIdMenuCategoriesNewRouteImport
      parentRoute: typeof AppStoresStoreIdMenuRoute
    }
    '/_app/stores/$storeId/menu/categories/$categoryId/': {
      id: '/_app/stores/$storeId/menu/categories/$categoryId/'
      path: '/categories/$categoryId'
      fullPath: '/stores/$storeId/menu/categories/$categoryId'
      preLoaderRoute: typeof AppStoresStoreIdMenuCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof AppStoresStoreIdMenuRoute
    }
    '/_app/stores/$storeId/menu/categories/$categoryId/edit': {
      id: '/_app/stores/$storeId/menu/categories/$categoryId/edit'
      path: '/categories/$categoryId/edit'
      fullPath: '/stores/$storeId/menu/categories/$categoryId/edit'
      preLoaderRoute: typeof AppStoresStoreIdMenuCategoriesCategoryIdEditRouteImport
      parentRoute: typeof AppStoresStoreIdMenuRoute
    }
    '/_app/stores/$storeId/menu/categories/$categoryId/items/new': {
      id: '/_app/stores/$storeId/menu/categories/$categoryId/items/new'
      path: '/categories/$categoryId/items/new'
      fullPath: '/stores/$storeId/menu/categories/$categoryId/items/new'
      preLoaderRoute: typeof AppStoresStoreIdMenuCategoriesCategoryIdItemsNewRouteImport
      parentRoute: typeof AppStoresStoreIdMenuRoute
    }
    '/_app/stores/$storeId/menu/categories/$categoryId/items/$itemId': {
      id: '/_app/stores/$storeId/menu/categories/$categoryId/items/$itemId'
      path: '/categories/$categoryId/items/$itemId'
      fullPath: '/stores/$storeId/menu/categories/$categoryId/items/$itemId'
      preLoaderRoute: typeof AppStoresStoreIdMenuCategoriesCategoryIdItemsItemIdRouteImport
      parentRoute: typeof AppStoresStoreIdMenuRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAiRoute: typeof AppSettingsAiRoute
  AppSettingsLanguageRoute: typeof AppSettingsLanguageRoute
  AppSettingsPaymentsRoute: typeof AppSettingsPaymentsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAiRoute: AppSettingsAiRoute,
  AppSettingsLanguageRoute: AppSettingsLanguageRoute,
  AppSettingsPaymentsRoute: AppSettingsPaymentsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppStoresStoreIdMenuRouteChildren {
  AppStoresStoreIdMenuImportRoute: typeof AppStoresStoreIdMenuImportRoute
  AppStoresStoreIdMenuIndexRoute: typeof AppStoresStoreIdMenuIndexRoute
  AppStoresStoreIdMenuCategoriesNewRoute: typeof AppStoresStoreIdMenuCategoriesNewRoute
  AppStoresStoreIdMenuOptionsOptionGroupIdRoute: typeof AppStoresStoreIdMenuOptionsOptionGroupIdRoute
  AppStoresStoreIdMenuOptionsNewRoute: typeof AppStoresStoreIdMenuOptionsNewRoute
  AppStoresStoreIdMenuVatVatGroupIdRoute: typeof AppStoresStoreIdMenuVatVatGroupIdRoute
  AppStoresStoreIdMenuVatNewRoute: typeof AppStoresStoreIdMenuVatNewRoute
  AppStoresStoreIdMenuOptionsIndexRoute: typeof AppStoresStoreIdMenuOptionsIndexRoute
  AppStoresStoreIdMenuVatIndexRoute: typeof AppStoresStoreIdMenuVatIndexRoute
  AppStoresStoreIdMenuCategoriesCategoryIdEditRoute: typeof AppStoresStoreIdMenuCategoriesCategoryIdEditRoute
  AppStoresStoreIdMenuCategoriesCategoryIdIndexRoute: typeof AppStoresStoreIdMenuCategoriesCategoryIdIndexRoute
  AppStoresStoreIdMenuCategoriesCategoryIdItemsItemIdRoute: typeof AppStoresStoreIdMenuCategoriesCategoryIdItemsItemIdRoute
  AppStoresStoreIdMenuCategoriesCategoryIdItemsNewRoute: typeof AppStoresStoreIdMenuCategoriesCategoryIdItemsNewRoute
}

const AppStoresStoreIdMenuRouteChildren: AppStoresStoreIdMenuRouteChildren = {
  AppStoresStoreIdMenuImportRoute: AppStoresStoreIdMenuImportRoute,
  AppStoresStoreIdMenuIndexRoute: AppStoresStoreIdMenuIndexRoute,
  AppStoresStoreIdMenuCategoriesNewRoute:
    AppStoresStoreIdMenuCategoriesNewRoute,
  AppStoresStoreIdMenuOptionsOptionGroupIdRoute:
    AppStoresStoreIdMenuOptionsOptionGroupIdRoute,
  AppStoresStoreIdMenuOptionsNewRoute: AppStoresStoreIdMenuOptionsNewRoute,
  AppStoresStoreIdMenuVatVatGroupIdRoute:
    AppStoresStoreIdMenuVatVatGroupIdRoute,
  AppStoresStoreIdMenuVatNewRoute: AppStoresStoreIdMenuVatNewRoute,
  AppStoresStoreIdMenuOptionsIndexRoute: AppStoresStoreIdMenuOptionsIndexRoute,
  AppStoresStoreIdMenuVatIndexRoute: AppStoresStoreIdMenuVatIndexRoute,
  AppStoresStoreIdMenuCategoriesCategoryIdEditRoute:
    AppStoresStoreIdMenuCategoriesCategoryIdEditRoute,
  AppStoresStoreIdMenuCategoriesCategoryIdIndexRoute:
    AppStoresStoreIdMenuCategoriesCategoryIdIndexRoute,
  AppStoresStoreIdMenuCategoriesCategoryIdItemsItemIdRoute:
    AppStoresStoreIdMenuCategoriesCategoryIdItemsItemIdRoute,
  AppStoresStoreIdMenuCategoriesCategoryIdItemsNewRoute:
    AppStoresStoreIdMenuCategoriesCategoryIdItemsNewRoute,
}

const AppStoresStoreIdMenuRouteWithChildren =
  AppStoresStoreIdMenuRoute._addFileChildren(AppStoresStoreIdMenuRouteChildren)

interface AppStoresStoreIdServicePointsServicePointIdRouteChildren {
  AppStoresStoreIdServicePointsServicePointIdQrRoute: typeof AppStoresStoreIdServicePointsServicePointIdQrRoute
}

const AppStoresStoreIdServicePointsServicePointIdRouteChildren: AppStoresStoreIdServicePointsServicePointIdRouteChildren =
  {
    AppStoresStoreIdServicePointsServicePointIdQrRoute:
      AppStoresStoreIdServicePointsServicePointIdQrRoute,
  }

const AppStoresStoreIdServicePointsServicePointIdRouteWithChildren =
  AppStoresStoreIdServicePointsServicePointIdRoute._addFileChildren(
    AppStoresStoreIdServicePointsServicePointIdRouteChildren,
  )

interface AppStoresStoreIdServicePointsRouteChildren {
  AppStoresStoreIdServicePointsServicePointIdRoute: typeof AppStoresStoreIdServicePointsServicePointIdRouteWithChildren
  AppStoresStoreIdServicePointsBatchRoute: typeof AppStoresStoreIdServicePointsBatchRoute
  AppStoresStoreIdServicePointsNewRoute: typeof AppStoresStoreIdServicePointsNewRoute
  AppStoresStoreIdServicePointsIndexRoute: typeof AppStoresStoreIdServicePointsIndexRoute
}

const AppStoresStoreIdServicePointsRouteChildren: AppStoresStoreIdServicePointsRouteChildren =
  {
    AppStoresStoreIdServicePointsServicePointIdRoute:
      AppStoresStoreIdServicePointsServicePointIdRouteWithChildren,
    AppStoresStoreIdServicePointsBatchRoute:
      AppStoresStoreIdServicePointsBatchRoute,
    AppStoresStoreIdServicePointsNewRoute:
      AppStoresStoreIdServicePointsNewRoute,
    AppStoresStoreIdServicePointsIndexRoute:
      AppStoresStoreIdServicePointsIndexRoute,
  }

const AppStoresStoreIdServicePointsRouteWithChildren =
  AppStoresStoreIdServicePointsRoute._addFileChildren(
    AppStoresStoreIdServicePointsRouteChildren,
  )

interface AppStoresStoreIdSettingsRouteChildren {
  AppStoresStoreIdSettingsClosuresRoute: typeof AppStoresStoreIdSettingsClosuresRoute
  AppStoresStoreIdSettingsHoursRoute: typeof AppStoresStoreIdSettingsHoursRoute
  AppStoresStoreIdSettingsOrderTypesRoute: typeof AppStoresStoreIdSettingsOrderTypesRoute
  AppStoresStoreIdSettingsIndexRoute: typeof AppStoresStoreIdSettingsIndexRoute
}

const AppStoresStoreIdSettingsRouteChildren: AppStoresStoreIdSettingsRouteChildren =
  {
    AppStoresStoreIdSettingsClosuresRoute:
      AppStoresStoreIdSettingsClosuresRoute,
    AppStoresStoreIdSettingsHoursRoute: AppStoresStoreIdSettingsHoursRoute,
    AppStoresStoreIdSettingsOrderTypesRoute:
      AppStoresStoreIdSettingsOrderTypesRoute,
    AppStoresStoreIdSettingsIndexRoute: AppStoresStoreIdSettingsIndexRoute,
  }

const AppStoresStoreIdSettingsRouteWithChildren =
  AppStoresStoreIdSettingsRoute._addFileChildren(
    AppStoresStoreIdSettingsRouteChildren,
  )

interface AppStoresStoreIdRouteChildren {
  AppStoresStoreIdMenuRoute: typeof AppStoresStoreIdMenuRouteWithChildren
  AppStoresStoreIdServicePointsRoute: typeof AppStoresStoreIdServicePointsRouteWithChildren
  AppStoresStoreIdSettingsRoute: typeof AppStoresStoreIdSettingsRouteWithChildren
  AppStoresStoreIdOrdersOrderIdRoute: typeof AppStoresStoreIdOrdersOrderIdRoute
  AppStoresStoreIdKitchenIndexRoute: typeof AppStoresStoreIdKitchenIndexRoute
  AppStoresStoreIdOrdersIndexRoute: typeof AppStoresStoreIdOrdersIndexRoute
}

const AppStoresStoreIdRouteChildren: AppStoresStoreIdRouteChildren = {
  AppStoresStoreIdMenuRoute: AppStoresStoreIdMenuRouteWithChildren,
  AppStoresStoreIdServicePointsRoute:
    AppStoresStoreIdServicePointsRouteWithChildren,
  AppStoresStoreIdSettingsRoute: AppStoresStoreIdSettingsRouteWithChildren,
  AppStoresStoreIdOrdersOrderIdRoute: AppStoresStoreIdOrdersOrderIdRoute,
  AppStoresStoreIdKitchenIndexRoute: AppStoresStoreIdKitchenIndexRoute,
  AppStoresStoreIdOrdersIndexRoute: AppStoresStoreIdOrdersIndexRoute,
}

const AppStoresStoreIdRouteWithChildren =
  AppStoresStoreIdRoute._addFileChildren(AppStoresStoreIdRouteChildren)

interface AppRouteChildren {
  AppKitchenRoute: typeof AppKitchenRoute
  AppMenuRoute: typeof AppMenuRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppStoresStoreIdRoute: typeof AppStoresStoreIdRouteWithChildren
  AppStoresNewRoute: typeof AppStoresNewRoute
  AppHelpIndexRoute: typeof AppHelpIndexRoute
  AppStoresIndexRoute: typeof AppStoresIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppKitchenRoute: AppKitchenRoute,
  AppMenuRoute: AppMenuRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppStoresStoreIdRoute: AppStoresStoreIdRouteWithChildren,
  AppStoresNewRoute: AppStoresNewRoute,
  AppHelpIndexRoute: AppHelpIndexRoute,
  AppStoresIndexRoute: AppStoresIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicOnboardingRoute: typeof PublicOnboardingRoute
  PublicLegalImpressumRoute: typeof PublicLegalImpressumRoute
  PublicLegalPrivacyRoute: typeof PublicLegalPrivacyRoute
  PublicAuthMerchantLoginRoute: typeof PublicAuthMerchantLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicOnboardingRoute: PublicOnboardingRoute,
  PublicLegalImpressumRoute: PublicLegalImpressumRoute,
  PublicLegalPrivacyRoute: PublicLegalPrivacyRoute,
  PublicAuthMerchantLoginRoute: PublicAuthMerchantLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
