/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as PublicOnboardingRouteImport } from './routes/_public/onboarding'
import { Route as AppStoresIndexRouteImport } from './routes/_app/stores/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppMenuIndexRouteImport } from './routes/_app/menu/index'
import { Route as AppKitchenIndexRouteImport } from './routes/_app/kitchen/index'
import { Route as AppHelpIndexRouteImport } from './routes/_app/help/index'
import { Route as PublicLegalPrivacyRouteImport } from './routes/_public/legal/privacy'
import { Route as PublicLegalImpressumRouteImport } from './routes/_public/legal/impressum'
import { Route as AppStoresNewRouteImport } from './routes/_app/stores/new'
import { Route as AppStoresStoreIdRouteImport } from './routes/_app/stores/$storeId'
import { Route as AppSettingsPaymentsRouteImport } from './routes/_app/settings/payments'
import { Route as AppSettingsMerchantRouteImport } from './routes/_app/settings/merchant'
import { Route as AppSettingsAiRecommendationsRouteImport } from './routes/_app/settings/ai-recommendations'
import { Route as AppOrdersOrderIdRouteImport } from './routes/_app/orders/$orderId'
import { Route as AppMenuImportRouteImport } from './routes/_app/menu/import'
import { Route as AppMenuVatIndexRouteImport } from './routes/_app/menu/vat/index'
import { Route as AppMenuOptionsIndexRouteImport } from './routes/_app/menu/options/index'
import { Route as PublicAuthMerchantLoginRouteImport } from './routes/_public/auth/merchant/login'
import { Route as AppMenuVatNewRouteImport } from './routes/_app/menu/vat/new'
import { Route as AppMenuVatVatGroupIdRouteImport } from './routes/_app/menu/vat/$vatGroupId'
import { Route as AppMenuOptionsNewRouteImport } from './routes/_app/menu/options/new'
import { Route as AppMenuOptionsOptionGroupIdRouteImport } from './routes/_app/menu/options/$optionGroupId'
import { Route as AppMenuCategoriesNewRouteImport } from './routes/_app/menu/categories/new'
import { Route as AppMenuCategoriesCategoryIdIndexRouteImport } from './routes/_app/menu/categories/$categoryId/index'
import { Route as AppMenuCategoriesCategoryIdEditRouteImport } from './routes/_app/menu/categories/$categoryId/edit'
import { Route as AppMenuCategoriesCategoryIdItemsNewRouteImport } from './routes/_app/menu/categories/$categoryId/items/new'
import { Route as AppMenuCategoriesCategoryIdItemsItemIdRouteImport } from './routes/_app/menu/categories/$categoryId/items/$itemId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PublicOnboardingRoute = PublicOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PublicRoute,
} as any)
const AppStoresIndexRoute = AppStoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuIndexRoute = AppMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AppRoute,
} as any)
const AppKitchenIndexRoute = AppKitchenIndexRouteImport.update({
  id: '/kitchen/',
  path: '/kitchen/',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpIndexRoute = AppHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => AppRoute,
} as any)
const PublicLegalPrivacyRoute = PublicLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLegalImpressumRoute = PublicLegalImpressumRouteImport.update({
  id: '/legal/impressum',
  path: '/legal/impressum',
  getParentRoute: () => PublicRoute,
} as any)
const AppStoresNewRoute = AppStoresNewRouteImport.update({
  id: '/stores/new',
  path: '/stores/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresStoreIdRoute = AppStoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPaymentsRoute = AppSettingsPaymentsRouteImport.update({
  id: '/settings/payments',
  path: '/settings/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMerchantRoute = AppSettingsMerchantRouteImport.update({
  id: '/settings/merchant',
  path: '/settings/merchant',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAiRecommendationsRoute =
  AppSettingsAiRecommendationsRouteImport.update({
    id: '/settings/ai-recommendations',
    path: '/settings/ai-recommendations',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuImportRoute = AppMenuImportRouteImport.update({
  id: '/menu/import',
  path: '/menu/import',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuVatIndexRoute = AppMenuVatIndexRouteImport.update({
  id: '/menu/vat/',
  path: '/menu/vat/',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuOptionsIndexRoute = AppMenuOptionsIndexRouteImport.update({
  id: '/menu/options/',
  path: '/menu/options/',
  getParentRoute: () => AppRoute,
} as any)
const PublicAuthMerchantLoginRoute = PublicAuthMerchantLoginRouteImport.update({
  id: '/auth/merchant/login',
  path: '/auth/merchant/login',
  getParentRoute: () => PublicRoute,
} as any)
const AppMenuVatNewRoute = AppMenuVatNewRouteImport.update({
  id: '/menu/vat/new',
  path: '/menu/vat/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuVatVatGroupIdRoute = AppMenuVatVatGroupIdRouteImport.update({
  id: '/menu/vat/$vatGroupId',
  path: '/menu/vat/$vatGroupId',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuOptionsNewRoute = AppMenuOptionsNewRouteImport.update({
  id: '/menu/options/new',
  path: '/menu/options/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuOptionsOptionGroupIdRoute =
  AppMenuOptionsOptionGroupIdRouteImport.update({
    id: '/menu/options/$optionGroupId',
    path: '/menu/options/$optionGroupId',
    getParentRoute: () => AppRoute,
  } as any)
const AppMenuCategoriesNewRoute = AppMenuCategoriesNewRouteImport.update({
  id: '/menu/categories/new',
  path: '/menu/categories/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuCategoriesCategoryIdIndexRoute =
  AppMenuCategoriesCategoryIdIndexRouteImport.update({
    id: '/menu/categories/$categoryId/',
    path: '/menu/categories/$categoryId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppMenuCategoriesCategoryIdEditRoute =
  AppMenuCategoriesCategoryIdEditRouteImport.update({
    id: '/menu/categories/$categoryId/edit',
    path: '/menu/categories/$categoryId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppMenuCategoriesCategoryIdItemsNewRoute =
  AppMenuCategoriesCategoryIdItemsNewRouteImport.update({
    id: '/menu/categories/$categoryId/items/new',
    path: '/menu/categories/$categoryId/items/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppMenuCategoriesCategoryIdItemsItemIdRoute =
  AppMenuCategoriesCategoryIdItemsItemIdRouteImport.update({
    id: '/menu/categories/$categoryId/items/$itemId',
    path: '/menu/categories/$categoryId/items/$itemId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/onboarding': typeof PublicOnboardingRoute
  '/': typeof AppIndexRoute
  '/menu/import': typeof AppMenuImportRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/settings/ai-recommendations': typeof AppSettingsAiRecommendationsRoute
  '/settings/merchant': typeof AppSettingsMerchantRoute
  '/settings/payments': typeof AppSettingsPaymentsRoute
  '/stores/$storeId': typeof AppStoresStoreIdRoute
  '/stores/new': typeof AppStoresNewRoute
  '/legal/impressum': typeof PublicLegalImpressumRoute
  '/legal/privacy': typeof PublicLegalPrivacyRoute
  '/help': typeof AppHelpIndexRoute
  '/kitchen': typeof AppKitchenIndexRoute
  '/menu': typeof AppMenuIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/stores': typeof AppStoresIndexRoute
  '/menu/categories/new': typeof AppMenuCategoriesNewRoute
  '/menu/options/$optionGroupId': typeof AppMenuOptionsOptionGroupIdRoute
  '/menu/options/new': typeof AppMenuOptionsNewRoute
  '/menu/vat/$vatGroupId': typeof AppMenuVatVatGroupIdRoute
  '/menu/vat/new': typeof AppMenuVatNewRoute
  '/auth/merchant/login': typeof PublicAuthMerchantLoginRoute
  '/menu/options': typeof AppMenuOptionsIndexRoute
  '/menu/vat': typeof AppMenuVatIndexRoute
  '/menu/categories/$categoryId/edit': typeof AppMenuCategoriesCategoryIdEditRoute
  '/menu/categories/$categoryId': typeof AppMenuCategoriesCategoryIdIndexRoute
  '/menu/categories/$categoryId/items/$itemId': typeof AppMenuCategoriesCategoryIdItemsItemIdRoute
  '/menu/categories/$categoryId/items/new': typeof AppMenuCategoriesCategoryIdItemsNewRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof PublicOnboardingRoute
  '/': typeof AppIndexRoute
  '/menu/import': typeof AppMenuImportRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/settings/ai-recommendations': typeof AppSettingsAiRecommendationsRoute
  '/settings/merchant': typeof AppSettingsMerchantRoute
  '/settings/payments': typeof AppSettingsPaymentsRoute
  '/stores/$storeId': typeof AppStoresStoreIdRoute
  '/stores/new': typeof AppStoresNewRoute
  '/legal/impressum': typeof PublicLegalImpressumRoute
  '/legal/privacy': typeof PublicLegalPrivacyRoute
  '/help': typeof AppHelpIndexRoute
  '/kitchen': typeof AppKitchenIndexRoute
  '/menu': typeof AppMenuIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/stores': typeof AppStoresIndexRoute
  '/menu/categories/new': typeof AppMenuCategoriesNewRoute
  '/menu/options/$optionGroupId': typeof AppMenuOptionsOptionGroupIdRoute
  '/menu/options/new': typeof AppMenuOptionsNewRoute
  '/menu/vat/$vatGroupId': typeof AppMenuVatVatGroupIdRoute
  '/menu/vat/new': typeof AppMenuVatNewRoute
  '/auth/merchant/login': typeof PublicAuthMerchantLoginRoute
  '/menu/options': typeof AppMenuOptionsIndexRoute
  '/menu/vat': typeof AppMenuVatIndexRoute
  '/menu/categories/$categoryId/edit': typeof AppMenuCategoriesCategoryIdEditRoute
  '/menu/categories/$categoryId': typeof AppMenuCategoriesCategoryIdIndexRoute
  '/menu/categories/$categoryId/items/$itemId': typeof AppMenuCategoriesCategoryIdItemsItemIdRoute
  '/menu/categories/$categoryId/items/new': typeof AppMenuCategoriesCategoryIdItemsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/onboarding': typeof PublicOnboardingRoute
  '/_app/': typeof AppIndexRoute
  '/_app/menu/import': typeof AppMenuImportRoute
  '/_app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/_app/settings/ai-recommendations': typeof AppSettingsAiRecommendationsRoute
  '/_app/settings/merchant': typeof AppSettingsMerchantRoute
  '/_app/settings/payments': typeof AppSettingsPaymentsRoute
  '/_app/stores/$storeId': typeof AppStoresStoreIdRoute
  '/_app/stores/new': typeof AppStoresNewRoute
  '/_public/legal/impressum': typeof PublicLegalImpressumRoute
  '/_public/legal/privacy': typeof PublicLegalPrivacyRoute
  '/_app/help/': typeof AppHelpIndexRoute
  '/_app/kitchen/': typeof AppKitchenIndexRoute
  '/_app/menu/': typeof AppMenuIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/stores/': typeof AppStoresIndexRoute
  '/_app/menu/categories/new': typeof AppMenuCategoriesNewRoute
  '/_app/menu/options/$optionGroupId': typeof AppMenuOptionsOptionGroupIdRoute
  '/_app/menu/options/new': typeof AppMenuOptionsNewRoute
  '/_app/menu/vat/$vatGroupId': typeof AppMenuVatVatGroupIdRoute
  '/_app/menu/vat/new': typeof AppMenuVatNewRoute
  '/_public/auth/merchant/login': typeof PublicAuthMerchantLoginRoute
  '/_app/menu/options/': typeof AppMenuOptionsIndexRoute
  '/_app/menu/vat/': typeof AppMenuVatIndexRoute
  '/_app/menu/categories/$categoryId/edit': typeof AppMenuCategoriesCategoryIdEditRoute
  '/_app/menu/categories/$categoryId/': typeof AppMenuCategoriesCategoryIdIndexRoute
  '/_app/menu/categories/$categoryId/items/$itemId': typeof AppMenuCategoriesCategoryIdItemsItemIdRoute
  '/_app/menu/categories/$categoryId/items/new': typeof AppMenuCategoriesCategoryIdItemsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/onboarding'
    | '/'
    | '/menu/import'
    | '/orders/$orderId'
    | '/settings/ai-recommendations'
    | '/settings/merchant'
    | '/settings/payments'
    | '/stores/$storeId'
    | '/stores/new'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/help'
    | '/kitchen'
    | '/menu'
    | '/orders'
    | '/settings'
    | '/stores'
    | '/menu/categories/new'
    | '/menu/options/$optionGroupId'
    | '/menu/options/new'
    | '/menu/vat/$vatGroupId'
    | '/menu/vat/new'
    | '/auth/merchant/login'
    | '/menu/options'
    | '/menu/vat'
    | '/menu/categories/$categoryId/edit'
    | '/menu/categories/$categoryId'
    | '/menu/categories/$categoryId/items/$itemId'
    | '/menu/categories/$categoryId/items/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/'
    | '/menu/import'
    | '/orders/$orderId'
    | '/settings/ai-recommendations'
    | '/settings/merchant'
    | '/settings/payments'
    | '/stores/$storeId'
    | '/stores/new'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/help'
    | '/kitchen'
    | '/menu'
    | '/orders'
    | '/settings'
    | '/stores'
    | '/menu/categories/new'
    | '/menu/options/$optionGroupId'
    | '/menu/options/new'
    | '/menu/vat/$vatGroupId'
    | '/menu/vat/new'
    | '/auth/merchant/login'
    | '/menu/options'
    | '/menu/vat'
    | '/menu/categories/$categoryId/edit'
    | '/menu/categories/$categoryId'
    | '/menu/categories/$categoryId/items/$itemId'
    | '/menu/categories/$categoryId/items/new'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_public/onboarding'
    | '/_app/'
    | '/_app/menu/import'
    | '/_app/orders/$orderId'
    | '/_app/settings/ai-recommendations'
    | '/_app/settings/merchant'
    | '/_app/settings/payments'
    | '/_app/stores/$storeId'
    | '/_app/stores/new'
    | '/_public/legal/impressum'
    | '/_public/legal/privacy'
    | '/_app/help/'
    | '/_app/kitchen/'
    | '/_app/menu/'
    | '/_app/orders/'
    | '/_app/settings/'
    | '/_app/stores/'
    | '/_app/menu/categories/new'
    | '/_app/menu/options/$optionGroupId'
    | '/_app/menu/options/new'
    | '/_app/menu/vat/$vatGroupId'
    | '/_app/menu/vat/new'
    | '/_public/auth/merchant/login'
    | '/_app/menu/options/'
    | '/_app/menu/vat/'
    | '/_app/menu/categories/$categoryId/edit'
    | '/_app/menu/categories/$categoryId/'
    | '/_app/menu/categories/$categoryId/items/$itemId'
    | '/_app/menu/categories/$categoryId/items/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/onboarding': {
      id: '/_public/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof PublicOnboardingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/stores/': {
      id: '/_app/stores/'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AppStoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/': {
      id: '/_app/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AppMenuIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kitchen/': {
      id: '/_app/kitchen/'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AppKitchenIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help/': {
      id: '/_app/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/legal/privacy': {
      id: '/_public/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof PublicLegalPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/legal/impressum': {
      id: '/_public/legal/impressum'
      path: '/legal/impressum'
      fullPath: '/legal/impressum'
      preLoaderRoute: typeof PublicLegalImpressumRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/stores/new': {
      id: '/_app/stores/new'
      path: '/stores/new'
      fullPath: '/stores/new'
      preLoaderRoute: typeof AppStoresNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stores/$storeId': {
      id: '/_app/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof AppStoresStoreIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/payments': {
      id: '/_app/settings/payments'
      path: '/settings/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof AppSettingsPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/merchant': {
      id: '/_app/settings/merchant'
      path: '/settings/merchant'
      fullPath: '/settings/merchant'
      preLoaderRoute: typeof AppSettingsMerchantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/ai-recommendations': {
      id: '/_app/settings/ai-recommendations'
      path: '/settings/ai-recommendations'
      fullPath: '/settings/ai-recommendations'
      preLoaderRoute: typeof AppSettingsAiRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$orderId': {
      id: '/_app/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/import': {
      id: '/_app/menu/import'
      path: '/menu/import'
      fullPath: '/menu/import'
      preLoaderRoute: typeof AppMenuImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/vat/': {
      id: '/_app/menu/vat/'
      path: '/menu/vat'
      fullPath: '/menu/vat'
      preLoaderRoute: typeof AppMenuVatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/options/': {
      id: '/_app/menu/options/'
      path: '/menu/options'
      fullPath: '/menu/options'
      preLoaderRoute: typeof AppMenuOptionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/auth/merchant/login': {
      id: '/_public/auth/merchant/login'
      path: '/auth/merchant/login'
      fullPath: '/auth/merchant/login'
      preLoaderRoute: typeof PublicAuthMerchantLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/menu/vat/new': {
      id: '/_app/menu/vat/new'
      path: '/menu/vat/new'
      fullPath: '/menu/vat/new'
      preLoaderRoute: typeof AppMenuVatNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/vat/$vatGroupId': {
      id: '/_app/menu/vat/$vatGroupId'
      path: '/menu/vat/$vatGroupId'
      fullPath: '/menu/vat/$vatGroupId'
      preLoaderRoute: typeof AppMenuVatVatGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/options/new': {
      id: '/_app/menu/options/new'
      path: '/menu/options/new'
      fullPath: '/menu/options/new'
      preLoaderRoute: typeof AppMenuOptionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/options/$optionGroupId': {
      id: '/_app/menu/options/$optionGroupId'
      path: '/menu/options/$optionGroupId'
      fullPath: '/menu/options/$optionGroupId'
      preLoaderRoute: typeof AppMenuOptionsOptionGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/categories/new': {
      id: '/_app/menu/categories/new'
      path: '/menu/categories/new'
      fullPath: '/menu/categories/new'
      preLoaderRoute: typeof AppMenuCategoriesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/categories/$categoryId/': {
      id: '/_app/menu/categories/$categoryId/'
      path: '/menu/categories/$categoryId'
      fullPath: '/menu/categories/$categoryId'
      preLoaderRoute: typeof AppMenuCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/categories/$categoryId/edit': {
      id: '/_app/menu/categories/$categoryId/edit'
      path: '/menu/categories/$categoryId/edit'
      fullPath: '/menu/categories/$categoryId/edit'
      preLoaderRoute: typeof AppMenuCategoriesCategoryIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/categories/$categoryId/items/new': {
      id: '/_app/menu/categories/$categoryId/items/new'
      path: '/menu/categories/$categoryId/items/new'
      fullPath: '/menu/categories/$categoryId/items/new'
      preLoaderRoute: typeof AppMenuCategoriesCategoryIdItemsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/categories/$categoryId/items/$itemId': {
      id: '/_app/menu/categories/$categoryId/items/$itemId'
      path: '/menu/categories/$categoryId/items/$itemId'
      fullPath: '/menu/categories/$categoryId/items/$itemId'
      preLoaderRoute: typeof AppMenuCategoriesCategoryIdItemsItemIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppMenuImportRoute: typeof AppMenuImportRoute
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRoute
  AppSettingsAiRecommendationsRoute: typeof AppSettingsAiRecommendationsRoute
  AppSettingsMerchantRoute: typeof AppSettingsMerchantRoute
  AppSettingsPaymentsRoute: typeof AppSettingsPaymentsRoute
  AppStoresStoreIdRoute: typeof AppStoresStoreIdRoute
  AppStoresNewRoute: typeof AppStoresNewRoute
  AppHelpIndexRoute: typeof AppHelpIndexRoute
  AppKitchenIndexRoute: typeof AppKitchenIndexRoute
  AppMenuIndexRoute: typeof AppMenuIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppStoresIndexRoute: typeof AppStoresIndexRoute
  AppMenuCategoriesNewRoute: typeof AppMenuCategoriesNewRoute
  AppMenuOptionsOptionGroupIdRoute: typeof AppMenuOptionsOptionGroupIdRoute
  AppMenuOptionsNewRoute: typeof AppMenuOptionsNewRoute
  AppMenuVatVatGroupIdRoute: typeof AppMenuVatVatGroupIdRoute
  AppMenuVatNewRoute: typeof AppMenuVatNewRoute
  AppMenuOptionsIndexRoute: typeof AppMenuOptionsIndexRoute
  AppMenuVatIndexRoute: typeof AppMenuVatIndexRoute
  AppMenuCategoriesCategoryIdEditRoute: typeof AppMenuCategoriesCategoryIdEditRoute
  AppMenuCategoriesCategoryIdIndexRoute: typeof AppMenuCategoriesCategoryIdIndexRoute
  AppMenuCategoriesCategoryIdItemsItemIdRoute: typeof AppMenuCategoriesCategoryIdItemsItemIdRoute
  AppMenuCategoriesCategoryIdItemsNewRoute: typeof AppMenuCategoriesCategoryIdItemsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppMenuImportRoute: AppMenuImportRoute,
  AppOrdersOrderIdRoute: AppOrdersOrderIdRoute,
  AppSettingsAiRecommendationsRoute: AppSettingsAiRecommendationsRoute,
  AppSettingsMerchantRoute: AppSettingsMerchantRoute,
  AppSettingsPaymentsRoute: AppSettingsPaymentsRoute,
  AppStoresStoreIdRoute: AppStoresStoreIdRoute,
  AppStoresNewRoute: AppStoresNewRoute,
  AppHelpIndexRoute: AppHelpIndexRoute,
  AppKitchenIndexRoute: AppKitchenIndexRoute,
  AppMenuIndexRoute: AppMenuIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppStoresIndexRoute: AppStoresIndexRoute,
  AppMenuCategoriesNewRoute: AppMenuCategoriesNewRoute,
  AppMenuOptionsOptionGroupIdRoute: AppMenuOptionsOptionGroupIdRoute,
  AppMenuOptionsNewRoute: AppMenuOptionsNewRoute,
  AppMenuVatVatGroupIdRoute: AppMenuVatVatGroupIdRoute,
  AppMenuVatNewRoute: AppMenuVatNewRoute,
  AppMenuOptionsIndexRoute: AppMenuOptionsIndexRoute,
  AppMenuVatIndexRoute: AppMenuVatIndexRoute,
  AppMenuCategoriesCategoryIdEditRoute: AppMenuCategoriesCategoryIdEditRoute,
  AppMenuCategoriesCategoryIdIndexRoute: AppMenuCategoriesCategoryIdIndexRoute,
  AppMenuCategoriesCategoryIdItemsItemIdRoute:
    AppMenuCategoriesCategoryIdItemsItemIdRoute,
  AppMenuCategoriesCategoryIdItemsNewRoute:
    AppMenuCategoriesCategoryIdItemsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicOnboardingRoute: typeof PublicOnboardingRoute
  PublicLegalImpressumRoute: typeof PublicLegalImpressumRoute
  PublicLegalPrivacyRoute: typeof PublicLegalPrivacyRoute
  PublicAuthMerchantLoginRoute: typeof PublicAuthMerchantLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicOnboardingRoute: PublicOnboardingRoute,
  PublicLegalImpressumRoute: PublicLegalImpressumRoute,
  PublicLegalPrivacyRoute: PublicLegalPrivacyRoute,
  PublicAuthMerchantLoginRoute: PublicAuthMerchantLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
