/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlugRouteRouteImport } from './routes/$slug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as QShortCodeRouteImport } from './routes/q/$shortCode'
import { Route as SlugOrderingIndexRouteImport } from './routes/$slug/ordering/index'
import { Route as SlugOrderingReturnRouteImport } from './routes/$slug/ordering/return'
import { Route as SlugOrderOrderIdRouteImport } from './routes/$slug/order/$orderId'

const SlugRouteRoute = SlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRouteRoute,
} as any)
const QShortCodeRoute = QShortCodeRouteImport.update({
  id: '/q/$shortCode',
  path: '/q/$shortCode',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugOrderingIndexRoute = SlugOrderingIndexRouteImport.update({
  id: '/ordering/',
  path: '/ordering/',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugOrderingReturnRoute = SlugOrderingReturnRouteImport.update({
  id: '/ordering/return',
  path: '/ordering/return',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugOrderOrderIdRoute = SlugOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => SlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/q/$shortCode': typeof QShortCodeRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/order/$orderId': typeof SlugOrderOrderIdRoute
  '/$slug/ordering/return': typeof SlugOrderingReturnRoute
  '/$slug/ordering': typeof SlugOrderingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/q/$shortCode': typeof QShortCodeRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/order/$orderId': typeof SlugOrderOrderIdRoute
  '/$slug/ordering/return': typeof SlugOrderingReturnRoute
  '/$slug/ordering': typeof SlugOrderingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/q/$shortCode': typeof QShortCodeRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/order/$orderId': typeof SlugOrderOrderIdRoute
  '/$slug/ordering/return': typeof SlugOrderingReturnRoute
  '/$slug/ordering/': typeof SlugOrderingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/q/$shortCode'
    | '/$slug/'
    | '/$slug/order/$orderId'
    | '/$slug/ordering/return'
    | '/$slug/ordering'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/q/$shortCode'
    | '/$slug'
    | '/$slug/order/$orderId'
    | '/$slug/ordering/return'
    | '/$slug/ordering'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/q/$shortCode'
    | '/$slug/'
    | '/$slug/order/$orderId'
    | '/$slug/ordering/return'
    | '/$slug/ordering/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRouteRoute: typeof SlugRouteRouteWithChildren
  QShortCodeRoute: typeof QShortCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/q/$shortCode': {
      id: '/q/$shortCode'
      path: '/q/$shortCode'
      fullPath: '/q/$shortCode'
      preLoaderRoute: typeof QShortCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/ordering/': {
      id: '/$slug/ordering/'
      path: '/ordering'
      fullPath: '/$slug/ordering'
      preLoaderRoute: typeof SlugOrderingIndexRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/ordering/return': {
      id: '/$slug/ordering/return'
      path: '/ordering/return'
      fullPath: '/$slug/ordering/return'
      preLoaderRoute: typeof SlugOrderingReturnRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/order/$orderId': {
      id: '/$slug/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/$slug/order/$orderId'
      preLoaderRoute: typeof SlugOrderOrderIdRouteImport
      parentRoute: typeof SlugRouteRoute
    }
  }
}

interface SlugRouteRouteChildren {
  SlugIndexRoute: typeof SlugIndexRoute
  SlugOrderOrderIdRoute: typeof SlugOrderOrderIdRoute
  SlugOrderingReturnRoute: typeof SlugOrderingReturnRoute
  SlugOrderingIndexRoute: typeof SlugOrderingIndexRoute
}

const SlugRouteRouteChildren: SlugRouteRouteChildren = {
  SlugIndexRoute: SlugIndexRoute,
  SlugOrderOrderIdRoute: SlugOrderOrderIdRoute,
  SlugOrderingReturnRoute: SlugOrderingReturnRoute,
  SlugOrderingIndexRoute: SlugOrderingIndexRoute,
}

const SlugRouteRouteWithChildren = SlugRouteRoute._addFileChildren(
  SlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRouteRoute: SlugRouteRouteWithChildren,
  QShortCodeRoute: QShortCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
