/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as BusinessRouteRouteImport } from './routes/business/route'
import { Route as SlugRouteRouteImport } from './routes/$slug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as QShortCodeRouteImport } from './routes/q/$shortCode'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalImpressumRouteImport } from './routes/legal/impressum'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as ConsoleStoresIndexRouteImport } from './routes/console/stores/index'
import { Route as ConsoleSettingsIndexRouteImport } from './routes/console/settings/index'
import { Route as ConsoleOrdersIndexRouteImport } from './routes/console/orders/index'
import { Route as ConsoleMenuIndexRouteImport } from './routes/console/menu/index'
import { Route as ConsoleKitchenIndexRouteImport } from './routes/console/kitchen/index'
import { Route as ConsoleHelpIndexRouteImport } from './routes/console/help/index'
import { Route as SlugCheckoutIndexRouteImport } from './routes/$slug/checkout/index'
import { Route as ConsoleStoresNewRouteImport } from './routes/console/stores/new'
import { Route as ConsoleStoresStoreIdRouteImport } from './routes/console/stores/$storeId'
import { Route as ConsoleSettingsSubscriptionRouteImport } from './routes/console/settings/subscription'
import { Route as ConsoleSettingsPaymentsRouteImport } from './routes/console/settings/payments'
import { Route as ConsoleSettingsMerchantRouteImport } from './routes/console/settings/merchant'
import { Route as ConsoleMenuImportRouteImport } from './routes/console/menu/import'
import { Route as AuthMerchantLoginRouteImport } from './routes/auth/merchant/login'
import { Route as ApiMollieCallbackRouteImport } from './routes/api.mollie.callback'
import { Route as ApiMenuImportUploadRouteImport } from './routes/api.menu-import.upload'
import { Route as ApiImagesUploadRouteImport } from './routes/api.images.upload'
import { Route as SlugOrderOrderIdRouteImport } from './routes/$slug/order/$orderId'
import { Route as SlugCheckoutReturnRouteImport } from './routes/$slug/checkout/return'
import { Route as ConsoleMenuItemsNewRouteImport } from './routes/console/menu/items/new'
import { Route as ConsoleMenuItemsItemIdRouteImport } from './routes/console/menu/items/$itemId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRouteRoute = BusinessRouteRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRouteRoute = SlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRouteRoute,
} as any)
const QShortCodeRoute = QShortCodeRouteImport.update({
  id: '/q/$shortCode',
  path: '/q/$shortCode',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalImpressumRoute = LegalImpressumRouteImport.update({
  id: '/legal/impressum',
  path: '/legal/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleStoresIndexRoute = ConsoleStoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSettingsIndexRoute = ConsoleSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleOrdersIndexRoute = ConsoleOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleMenuIndexRoute = ConsoleMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleKitchenIndexRoute = ConsoleKitchenIndexRouteImport.update({
  id: '/kitchen/',
  path: '/kitchen/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleHelpIndexRoute = ConsoleHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const SlugCheckoutIndexRoute = SlugCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => SlugRouteRoute,
} as any)
const ConsoleStoresNewRoute = ConsoleStoresNewRouteImport.update({
  id: '/stores/new',
  path: '/stores/new',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleStoresStoreIdRoute = ConsoleStoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSettingsSubscriptionRoute =
  ConsoleSettingsSubscriptionRouteImport.update({
    id: '/settings/subscription',
    path: '/settings/subscription',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleSettingsPaymentsRoute = ConsoleSettingsPaymentsRouteImport.update({
  id: '/settings/payments',
  path: '/settings/payments',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSettingsMerchantRoute = ConsoleSettingsMerchantRouteImport.update({
  id: '/settings/merchant',
  path: '/settings/merchant',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleMenuImportRoute = ConsoleMenuImportRouteImport.update({
  id: '/menu/import',
  path: '/menu/import',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const AuthMerchantLoginRoute = AuthMerchantLoginRouteImport.update({
  id: '/auth/merchant/login',
  path: '/auth/merchant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMollieCallbackRoute = ApiMollieCallbackRouteImport.update({
  id: '/api/mollie/callback',
  path: '/api/mollie/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMenuImportUploadRoute = ApiMenuImportUploadRouteImport.update({
  id: '/api/menu-import/upload',
  path: '/api/menu-import/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesUploadRoute = ApiImagesUploadRouteImport.update({
  id: '/api/images/upload',
  path: '/api/images/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugOrderOrderIdRoute = SlugOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugCheckoutReturnRoute = SlugCheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => SlugRouteRoute,
} as any)
const ConsoleMenuItemsNewRoute = ConsoleMenuItemsNewRouteImport.update({
  id: '/menu/items/new',
  path: '/menu/items/new',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleMenuItemsItemIdRoute = ConsoleMenuItemsItemIdRouteImport.update({
  id: '/menu/items/$itemId',
  path: '/menu/items/$itemId',
  getParentRoute: () => ConsoleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/business': typeof BusinessRouteRouteWithChildren
  '/console': typeof ConsoleRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/live': typeof LiveRoute
  '/onboarding': typeof OnboardingRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/q/$shortCode': typeof QShortCodeRoute
  '/$slug/': typeof SlugIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/$slug/checkout/return': typeof SlugCheckoutReturnRoute
  '/$slug/order/$orderId': typeof SlugOrderOrderIdRoute
  '/api/images/upload': typeof ApiImagesUploadRoute
  '/api/menu-import/upload': typeof ApiMenuImportUploadRoute
  '/api/mollie/callback': typeof ApiMollieCallbackRoute
  '/auth/merchant/login': typeof AuthMerchantLoginRoute
  '/console/menu/import': typeof ConsoleMenuImportRoute
  '/console/settings/merchant': typeof ConsoleSettingsMerchantRoute
  '/console/settings/payments': typeof ConsoleSettingsPaymentsRoute
  '/console/settings/subscription': typeof ConsoleSettingsSubscriptionRoute
  '/console/stores/$storeId': typeof ConsoleStoresStoreIdRoute
  '/console/stores/new': typeof ConsoleStoresNewRoute
  '/$slug/checkout': typeof SlugCheckoutIndexRoute
  '/console/help': typeof ConsoleHelpIndexRoute
  '/console/kitchen': typeof ConsoleKitchenIndexRoute
  '/console/menu': typeof ConsoleMenuIndexRoute
  '/console/orders': typeof ConsoleOrdersIndexRoute
  '/console/settings': typeof ConsoleSettingsIndexRoute
  '/console/stores': typeof ConsoleStoresIndexRoute
  '/console/menu/items/$itemId': typeof ConsoleMenuItemsItemIdRoute
  '/console/menu/items/new': typeof ConsoleMenuItemsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/live': typeof LiveRoute
  '/onboarding': typeof OnboardingRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/q/$shortCode': typeof QShortCodeRoute
  '/$slug': typeof SlugIndexRoute
  '/business': typeof BusinessIndexRoute
  '/console': typeof ConsoleIndexRoute
  '/$slug/checkout/return': typeof SlugCheckoutReturnRoute
  '/$slug/order/$orderId': typeof SlugOrderOrderIdRoute
  '/api/images/upload': typeof ApiImagesUploadRoute
  '/api/menu-import/upload': typeof ApiMenuImportUploadRoute
  '/api/mollie/callback': typeof ApiMollieCallbackRoute
  '/auth/merchant/login': typeof AuthMerchantLoginRoute
  '/console/menu/import': typeof ConsoleMenuImportRoute
  '/console/settings/merchant': typeof ConsoleSettingsMerchantRoute
  '/console/settings/payments': typeof ConsoleSettingsPaymentsRoute
  '/console/settings/subscription': typeof ConsoleSettingsSubscriptionRoute
  '/console/stores/$storeId': typeof ConsoleStoresStoreIdRoute
  '/console/stores/new': typeof ConsoleStoresNewRoute
  '/$slug/checkout': typeof SlugCheckoutIndexRoute
  '/console/help': typeof ConsoleHelpIndexRoute
  '/console/kitchen': typeof ConsoleKitchenIndexRoute
  '/console/menu': typeof ConsoleMenuIndexRoute
  '/console/orders': typeof ConsoleOrdersIndexRoute
  '/console/settings': typeof ConsoleSettingsIndexRoute
  '/console/stores': typeof ConsoleStoresIndexRoute
  '/console/menu/items/$itemId': typeof ConsoleMenuItemsItemIdRoute
  '/console/menu/items/new': typeof ConsoleMenuItemsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/business': typeof BusinessRouteRouteWithChildren
  '/console': typeof ConsoleRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/live': typeof LiveRoute
  '/onboarding': typeof OnboardingRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/q/$shortCode': typeof QShortCodeRoute
  '/$slug/': typeof SlugIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/$slug/checkout/return': typeof SlugCheckoutReturnRoute
  '/$slug/order/$orderId': typeof SlugOrderOrderIdRoute
  '/api/images/upload': typeof ApiImagesUploadRoute
  '/api/menu-import/upload': typeof ApiMenuImportUploadRoute
  '/api/mollie/callback': typeof ApiMollieCallbackRoute
  '/auth/merchant/login': typeof AuthMerchantLoginRoute
  '/console/menu/import': typeof ConsoleMenuImportRoute
  '/console/settings/merchant': typeof ConsoleSettingsMerchantRoute
  '/console/settings/payments': typeof ConsoleSettingsPaymentsRoute
  '/console/settings/subscription': typeof ConsoleSettingsSubscriptionRoute
  '/console/stores/$storeId': typeof ConsoleStoresStoreIdRoute
  '/console/stores/new': typeof ConsoleStoresNewRoute
  '/$slug/checkout/': typeof SlugCheckoutIndexRoute
  '/console/help/': typeof ConsoleHelpIndexRoute
  '/console/kitchen/': typeof ConsoleKitchenIndexRoute
  '/console/menu/': typeof ConsoleMenuIndexRoute
  '/console/orders/': typeof ConsoleOrdersIndexRoute
  '/console/settings/': typeof ConsoleSettingsIndexRoute
  '/console/stores/': typeof ConsoleStoresIndexRoute
  '/console/menu/items/$itemId': typeof ConsoleMenuItemsItemIdRoute
  '/console/menu/items/new': typeof ConsoleMenuItemsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/business'
    | '/console'
    | '/health'
    | '/live'
    | '/onboarding'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/q/$shortCode'
    | '/$slug/'
    | '/business/'
    | '/console/'
    | '/$slug/checkout/return'
    | '/$slug/order/$orderId'
    | '/api/images/upload'
    | '/api/menu-import/upload'
    | '/api/mollie/callback'
    | '/auth/merchant/login'
    | '/console/menu/import'
    | '/console/settings/merchant'
    | '/console/settings/payments'
    | '/console/settings/subscription'
    | '/console/stores/$storeId'
    | '/console/stores/new'
    | '/$slug/checkout'
    | '/console/help'
    | '/console/kitchen'
    | '/console/menu'
    | '/console/orders'
    | '/console/settings'
    | '/console/stores'
    | '/console/menu/items/$itemId'
    | '/console/menu/items/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/live'
    | '/onboarding'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/q/$shortCode'
    | '/$slug'
    | '/business'
    | '/console'
    | '/$slug/checkout/return'
    | '/$slug/order/$orderId'
    | '/api/images/upload'
    | '/api/menu-import/upload'
    | '/api/mollie/callback'
    | '/auth/merchant/login'
    | '/console/menu/import'
    | '/console/settings/merchant'
    | '/console/settings/payments'
    | '/console/settings/subscription'
    | '/console/stores/$storeId'
    | '/console/stores/new'
    | '/$slug/checkout'
    | '/console/help'
    | '/console/kitchen'
    | '/console/menu'
    | '/console/orders'
    | '/console/settings'
    | '/console/stores'
    | '/console/menu/items/$itemId'
    | '/console/menu/items/new'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/business'
    | '/console'
    | '/health'
    | '/live'
    | '/onboarding'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/q/$shortCode'
    | '/$slug/'
    | '/business/'
    | '/console/'
    | '/$slug/checkout/return'
    | '/$slug/order/$orderId'
    | '/api/images/upload'
    | '/api/menu-import/upload'
    | '/api/mollie/callback'
    | '/auth/merchant/login'
    | '/console/menu/import'
    | '/console/settings/merchant'
    | '/console/settings/payments'
    | '/console/settings/subscription'
    | '/console/stores/$storeId'
    | '/console/stores/new'
    | '/$slug/checkout/'
    | '/console/help/'
    | '/console/kitchen/'
    | '/console/menu/'
    | '/console/orders/'
    | '/console/settings/'
    | '/console/stores/'
    | '/console/menu/items/$itemId'
    | '/console/menu/items/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRouteRoute: typeof SlugRouteRouteWithChildren
  BusinessRouteRoute: typeof BusinessRouteRouteWithChildren
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  LiveRoute: typeof LiveRoute
  OnboardingRoute: typeof OnboardingRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalImpressumRoute: typeof LegalImpressumRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  QShortCodeRoute: typeof QShortCodeRoute
  ApiImagesUploadRoute: typeof ApiImagesUploadRoute
  ApiMenuImportUploadRoute: typeof ApiMenuImportUploadRoute
  ApiMollieCallbackRoute: typeof ApiMollieCallbackRoute
  AuthMerchantLoginRoute: typeof AuthMerchantLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/q/$shortCode': {
      id: '/q/$shortCode'
      path: '/q/$shortCode'
      fullPath: '/q/$shortCode'
      preLoaderRoute: typeof QShortCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/impressum': {
      id: '/legal/impressum'
      path: '/legal/impressum'
      fullPath: '/legal/impressum'
      preLoaderRoute: typeof LegalImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/stores/': {
      id: '/console/stores/'
      path: '/stores'
      fullPath: '/console/stores'
      preLoaderRoute: typeof ConsoleStoresIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/settings/': {
      id: '/console/settings/'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ConsoleSettingsIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/orders/': {
      id: '/console/orders/'
      path: '/orders'
      fullPath: '/console/orders'
      preLoaderRoute: typeof ConsoleOrdersIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/menu/': {
      id: '/console/menu/'
      path: '/menu'
      fullPath: '/console/menu'
      preLoaderRoute: typeof ConsoleMenuIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/kitchen/': {
      id: '/console/kitchen/'
      path: '/kitchen'
      fullPath: '/console/kitchen'
      preLoaderRoute: typeof ConsoleKitchenIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/help/': {
      id: '/console/help/'
      path: '/help'
      fullPath: '/console/help'
      preLoaderRoute: typeof ConsoleHelpIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/$slug/checkout/': {
      id: '/$slug/checkout/'
      path: '/checkout'
      fullPath: '/$slug/checkout'
      preLoaderRoute: typeof SlugCheckoutIndexRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/console/stores/new': {
      id: '/console/stores/new'
      path: '/stores/new'
      fullPath: '/console/stores/new'
      preLoaderRoute: typeof ConsoleStoresNewRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/stores/$storeId': {
      id: '/console/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/console/stores/$storeId'
      preLoaderRoute: typeof ConsoleStoresStoreIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/settings/subscription': {
      id: '/console/settings/subscription'
      path: '/settings/subscription'
      fullPath: '/console/settings/subscription'
      preLoaderRoute: typeof ConsoleSettingsSubscriptionRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/settings/payments': {
      id: '/console/settings/payments'
      path: '/settings/payments'
      fullPath: '/console/settings/payments'
      preLoaderRoute: typeof ConsoleSettingsPaymentsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/settings/merchant': {
      id: '/console/settings/merchant'
      path: '/settings/merchant'
      fullPath: '/console/settings/merchant'
      preLoaderRoute: typeof ConsoleSettingsMerchantRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/menu/import': {
      id: '/console/menu/import'
      path: '/menu/import'
      fullPath: '/console/menu/import'
      preLoaderRoute: typeof ConsoleMenuImportRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/auth/merchant/login': {
      id: '/auth/merchant/login'
      path: '/auth/merchant/login'
      fullPath: '/auth/merchant/login'
      preLoaderRoute: typeof AuthMerchantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mollie/callback': {
      id: '/api/mollie/callback'
      path: '/api/mollie/callback'
      fullPath: '/api/mollie/callback'
      preLoaderRoute: typeof ApiMollieCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/menu-import/upload': {
      id: '/api/menu-import/upload'
      path: '/api/menu-import/upload'
      fullPath: '/api/menu-import/upload'
      preLoaderRoute: typeof ApiMenuImportUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/upload': {
      id: '/api/images/upload'
      path: '/api/images/upload'
      fullPath: '/api/images/upload'
      preLoaderRoute: typeof ApiImagesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/order/$orderId': {
      id: '/$slug/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/$slug/order/$orderId'
      preLoaderRoute: typeof SlugOrderOrderIdRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/checkout/return': {
      id: '/$slug/checkout/return'
      path: '/checkout/return'
      fullPath: '/$slug/checkout/return'
      preLoaderRoute: typeof SlugCheckoutReturnRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/console/menu/items/new': {
      id: '/console/menu/items/new'
      path: '/menu/items/new'
      fullPath: '/console/menu/items/new'
      preLoaderRoute: typeof ConsoleMenuItemsNewRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/menu/items/$itemId': {
      id: '/console/menu/items/$itemId'
      path: '/menu/items/$itemId'
      fullPath: '/console/menu/items/$itemId'
      preLoaderRoute: typeof ConsoleMenuItemsItemIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
  }
}

interface SlugRouteRouteChildren {
  SlugIndexRoute: typeof SlugIndexRoute
  SlugCheckoutReturnRoute: typeof SlugCheckoutReturnRoute
  SlugOrderOrderIdRoute: typeof SlugOrderOrderIdRoute
  SlugCheckoutIndexRoute: typeof SlugCheckoutIndexRoute
}

const SlugRouteRouteChildren: SlugRouteRouteChildren = {
  SlugIndexRoute: SlugIndexRoute,
  SlugCheckoutReturnRoute: SlugCheckoutReturnRoute,
  SlugOrderOrderIdRoute: SlugOrderOrderIdRoute,
  SlugCheckoutIndexRoute: SlugCheckoutIndexRoute,
}

const SlugRouteRouteWithChildren = SlugRouteRoute._addFileChildren(
  SlugRouteRouteChildren,
)

interface BusinessRouteRouteChildren {
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteRouteChildren: BusinessRouteRouteChildren = {
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteRouteWithChildren = BusinessRouteRoute._addFileChildren(
  BusinessRouteRouteChildren,
)

interface ConsoleRouteRouteChildren {
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleMenuImportRoute: typeof ConsoleMenuImportRoute
  ConsoleSettingsMerchantRoute: typeof ConsoleSettingsMerchantRoute
  ConsoleSettingsPaymentsRoute: typeof ConsoleSettingsPaymentsRoute
  ConsoleSettingsSubscriptionRoute: typeof ConsoleSettingsSubscriptionRoute
  ConsoleStoresStoreIdRoute: typeof ConsoleStoresStoreIdRoute
  ConsoleStoresNewRoute: typeof ConsoleStoresNewRoute
  ConsoleHelpIndexRoute: typeof ConsoleHelpIndexRoute
  ConsoleKitchenIndexRoute: typeof ConsoleKitchenIndexRoute
  ConsoleMenuIndexRoute: typeof ConsoleMenuIndexRoute
  ConsoleOrdersIndexRoute: typeof ConsoleOrdersIndexRoute
  ConsoleSettingsIndexRoute: typeof ConsoleSettingsIndexRoute
  ConsoleStoresIndexRoute: typeof ConsoleStoresIndexRoute
  ConsoleMenuItemsItemIdRoute: typeof ConsoleMenuItemsItemIdRoute
  ConsoleMenuItemsNewRoute: typeof ConsoleMenuItemsNewRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleMenuImportRoute: ConsoleMenuImportRoute,
  ConsoleSettingsMerchantRoute: ConsoleSettingsMerchantRoute,
  ConsoleSettingsPaymentsRoute: ConsoleSettingsPaymentsRoute,
  ConsoleSettingsSubscriptionRoute: ConsoleSettingsSubscriptionRoute,
  ConsoleStoresStoreIdRoute: ConsoleStoresStoreIdRoute,
  ConsoleStoresNewRoute: ConsoleStoresNewRoute,
  ConsoleHelpIndexRoute: ConsoleHelpIndexRoute,
  ConsoleKitchenIndexRoute: ConsoleKitchenIndexRoute,
  ConsoleMenuIndexRoute: ConsoleMenuIndexRoute,
  ConsoleOrdersIndexRoute: ConsoleOrdersIndexRoute,
  ConsoleSettingsIndexRoute: ConsoleSettingsIndexRoute,
  ConsoleStoresIndexRoute: ConsoleStoresIndexRoute,
  ConsoleMenuItemsItemIdRoute: ConsoleMenuItemsItemIdRoute,
  ConsoleMenuItemsNewRoute: ConsoleMenuItemsNewRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRouteRoute: SlugRouteRouteWithChildren,
  BusinessRouteRoute: BusinessRouteRouteWithChildren,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  LiveRoute: LiveRoute,
  OnboardingRoute: OnboardingRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalImpressumRoute: LegalImpressumRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  QShortCodeRoute: QShortCodeRoute,
  ApiImagesUploadRoute: ApiImagesUploadRoute,
  ApiMenuImportUploadRoute: ApiMenuImportUploadRoute,
  ApiMollieCallbackRoute: ApiMollieCallbackRoute,
  AuthMerchantLoginRoute: AuthMerchantLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
