/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ShopRouteRouteImport } from './routes/shop/route'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as BusinessRouteRouteImport } from './routes/business/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as QShortCodeRouteImport } from './routes/q/$shortCode'
import { Route as ConsoleOnboardingRouteImport } from './routes/console/onboarding'
import { Route as ShopSlugRouteRouteImport } from './routes/shop/$slug/route'
import { Route as ShopSlugIndexRouteImport } from './routes/shop/$slug/index'
import { Route as ConsoleStoresIndexRouteImport } from './routes/console/stores/index'
import { Route as ConsoleSettingsIndexRouteImport } from './routes/console/settings/index'
import { Route as ConsoleMenuIndexRouteImport } from './routes/console/menu/index'
import { Route as ConsoleStoresNewRouteImport } from './routes/console/stores/new'
import { Route as ConsoleStoresStoreIdRouteImport } from './routes/console/stores/$storeId'
import { Route as ConsoleSettingsSubscriptionRouteImport } from './routes/console/settings/subscription'
import { Route as ConsoleSettingsPaymentsRouteImport } from './routes/console/settings/payments'
import { Route as ConsoleSettingsMerchantRouteImport } from './routes/console/settings/merchant'
import { Route as ConsoleMenuImportRouteImport } from './routes/console/menu/import'
import { Route as ApiMollieCallbackRouteImport } from './routes/api.mollie.callback'
import { Route as ApiMenuImportUploadRouteImport } from './routes/api.menu-import.upload'
import { Route as ShopSlugCheckoutIndexRouteImport } from './routes/shop/$slug/checkout/index'
import { Route as ShopSlugOrderOrderIdRouteImport } from './routes/shop/$slug/order/$orderId'
import { Route as ShopSlugCheckoutReturnRouteImport } from './routes/shop/$slug/checkout/return'
import { Route as ConsoleMenuItemsNewRouteImport } from './routes/console/menu/items/new'
import { Route as ConsoleMenuItemsItemIdRouteImport } from './routes/console/menu/items/$itemId'

const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRouteRoute = ShopRouteRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRouteRoute = BusinessRouteRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRouteRoute,
} as any)
const QShortCodeRoute = QShortCodeRouteImport.update({
  id: '/q/$shortCode',
  path: '/q/$shortCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleOnboardingRoute = ConsoleOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ShopSlugRouteRoute = ShopSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ShopSlugIndexRoute = ShopSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopSlugRouteRoute,
} as any)
const ConsoleStoresIndexRoute = ConsoleStoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSettingsIndexRoute = ConsoleSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleMenuIndexRoute = ConsoleMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleStoresNewRoute = ConsoleStoresNewRouteImport.update({
  id: '/stores/new',
  path: '/stores/new',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleStoresStoreIdRoute = ConsoleStoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSettingsSubscriptionRoute =
  ConsoleSettingsSubscriptionRouteImport.update({
    id: '/settings/subscription',
    path: '/settings/subscription',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleSettingsPaymentsRoute = ConsoleSettingsPaymentsRouteImport.update({
  id: '/settings/payments',
  path: '/settings/payments',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSettingsMerchantRoute = ConsoleSettingsMerchantRouteImport.update({
  id: '/settings/merchant',
  path: '/settings/merchant',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleMenuImportRoute = ConsoleMenuImportRouteImport.update({
  id: '/menu/import',
  path: '/menu/import',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ApiMollieCallbackRoute = ApiMollieCallbackRouteImport.update({
  id: '/api/mollie/callback',
  path: '/api/mollie/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMenuImportUploadRoute = ApiMenuImportUploadRouteImport.update({
  id: '/api/menu-import/upload',
  path: '/api/menu-import/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugCheckoutIndexRoute = ShopSlugCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => ShopSlugRouteRoute,
} as any)
const ShopSlugOrderOrderIdRoute = ShopSlugOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => ShopSlugRouteRoute,
} as any)
const ShopSlugCheckoutReturnRoute = ShopSlugCheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => ShopSlugRouteRoute,
} as any)
const ConsoleMenuItemsNewRoute = ConsoleMenuItemsNewRouteImport.update({
  id: '/menu/items/new',
  path: '/menu/items/new',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleMenuItemsItemIdRoute = ConsoleMenuItemsItemIdRouteImport.update({
  id: '/menu/items/$itemId',
  path: '/menu/items/$itemId',
  getParentRoute: () => ConsoleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRouteRouteWithChildren
  '/console': typeof ConsoleRouteRouteWithChildren
  '/shop': typeof ShopRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/live': typeof LiveRoute
  '/shop/$slug': typeof ShopSlugRouteRouteWithChildren
  '/console/onboarding': typeof ConsoleOnboardingRoute
  '/q/$shortCode': typeof QShortCodeRoute
  '/business/': typeof BusinessIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/menu-import/upload': typeof ApiMenuImportUploadRoute
  '/api/mollie/callback': typeof ApiMollieCallbackRoute
  '/console/menu/import': typeof ConsoleMenuImportRoute
  '/console/settings/merchant': typeof ConsoleSettingsMerchantRoute
  '/console/settings/payments': typeof ConsoleSettingsPaymentsRoute
  '/console/settings/subscription': typeof ConsoleSettingsSubscriptionRoute
  '/console/stores/$storeId': typeof ConsoleStoresStoreIdRoute
  '/console/stores/new': typeof ConsoleStoresNewRoute
  '/console/menu': typeof ConsoleMenuIndexRoute
  '/console/settings': typeof ConsoleSettingsIndexRoute
  '/console/stores': typeof ConsoleStoresIndexRoute
  '/shop/$slug/': typeof ShopSlugIndexRoute
  '/console/menu/items/$itemId': typeof ConsoleMenuItemsItemIdRoute
  '/console/menu/items/new': typeof ConsoleMenuItemsNewRoute
  '/shop/$slug/checkout/return': typeof ShopSlugCheckoutReturnRoute
  '/shop/$slug/order/$orderId': typeof ShopSlugOrderOrderIdRoute
  '/shop/$slug/checkout': typeof ShopSlugCheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/live': typeof LiveRoute
  '/console/onboarding': typeof ConsoleOnboardingRoute
  '/q/$shortCode': typeof QShortCodeRoute
  '/business': typeof BusinessIndexRoute
  '/console': typeof ConsoleIndexRoute
  '/shop': typeof ShopIndexRoute
  '/api/menu-import/upload': typeof ApiMenuImportUploadRoute
  '/api/mollie/callback': typeof ApiMollieCallbackRoute
  '/console/menu/import': typeof ConsoleMenuImportRoute
  '/console/settings/merchant': typeof ConsoleSettingsMerchantRoute
  '/console/settings/payments': typeof ConsoleSettingsPaymentsRoute
  '/console/settings/subscription': typeof ConsoleSettingsSubscriptionRoute
  '/console/stores/$storeId': typeof ConsoleStoresStoreIdRoute
  '/console/stores/new': typeof ConsoleStoresNewRoute
  '/console/menu': typeof ConsoleMenuIndexRoute
  '/console/settings': typeof ConsoleSettingsIndexRoute
  '/console/stores': typeof ConsoleStoresIndexRoute
  '/shop/$slug': typeof ShopSlugIndexRoute
  '/console/menu/items/$itemId': typeof ConsoleMenuItemsItemIdRoute
  '/console/menu/items/new': typeof ConsoleMenuItemsNewRoute
  '/shop/$slug/checkout/return': typeof ShopSlugCheckoutReturnRoute
  '/shop/$slug/order/$orderId': typeof ShopSlugOrderOrderIdRoute
  '/shop/$slug/checkout': typeof ShopSlugCheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business': typeof BusinessRouteRouteWithChildren
  '/console': typeof ConsoleRouteRouteWithChildren
  '/shop': typeof ShopRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/live': typeof LiveRoute
  '/shop/$slug': typeof ShopSlugRouteRouteWithChildren
  '/console/onboarding': typeof ConsoleOnboardingRoute
  '/q/$shortCode': typeof QShortCodeRoute
  '/business/': typeof BusinessIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/menu-import/upload': typeof ApiMenuImportUploadRoute
  '/api/mollie/callback': typeof ApiMollieCallbackRoute
  '/console/menu/import': typeof ConsoleMenuImportRoute
  '/console/settings/merchant': typeof ConsoleSettingsMerchantRoute
  '/console/settings/payments': typeof ConsoleSettingsPaymentsRoute
  '/console/settings/subscription': typeof ConsoleSettingsSubscriptionRoute
  '/console/stores/$storeId': typeof ConsoleStoresStoreIdRoute
  '/console/stores/new': typeof ConsoleStoresNewRoute
  '/console/menu/': typeof ConsoleMenuIndexRoute
  '/console/settings/': typeof ConsoleSettingsIndexRoute
  '/console/stores/': typeof ConsoleStoresIndexRoute
  '/shop/$slug/': typeof ShopSlugIndexRoute
  '/console/menu/items/$itemId': typeof ConsoleMenuItemsItemIdRoute
  '/console/menu/items/new': typeof ConsoleMenuItemsNewRoute
  '/shop/$slug/checkout/return': typeof ShopSlugCheckoutReturnRoute
  '/shop/$slug/order/$orderId': typeof ShopSlugOrderOrderIdRoute
  '/shop/$slug/checkout/': typeof ShopSlugCheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business'
    | '/console'
    | '/shop'
    | '/health'
    | '/live'
    | '/shop/$slug'
    | '/console/onboarding'
    | '/q/$shortCode'
    | '/business/'
    | '/console/'
    | '/shop/'
    | '/api/menu-import/upload'
    | '/api/mollie/callback'
    | '/console/menu/import'
    | '/console/settings/merchant'
    | '/console/settings/payments'
    | '/console/settings/subscription'
    | '/console/stores/$storeId'
    | '/console/stores/new'
    | '/console/menu'
    | '/console/settings'
    | '/console/stores'
    | '/shop/$slug/'
    | '/console/menu/items/$itemId'
    | '/console/menu/items/new'
    | '/shop/$slug/checkout/return'
    | '/shop/$slug/order/$orderId'
    | '/shop/$slug/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/live'
    | '/console/onboarding'
    | '/q/$shortCode'
    | '/business'
    | '/console'
    | '/shop'
    | '/api/menu-import/upload'
    | '/api/mollie/callback'
    | '/console/menu/import'
    | '/console/settings/merchant'
    | '/console/settings/payments'
    | '/console/settings/subscription'
    | '/console/stores/$storeId'
    | '/console/stores/new'
    | '/console/menu'
    | '/console/settings'
    | '/console/stores'
    | '/shop/$slug'
    | '/console/menu/items/$itemId'
    | '/console/menu/items/new'
    | '/shop/$slug/checkout/return'
    | '/shop/$slug/order/$orderId'
    | '/shop/$slug/checkout'
  id:
    | '__root__'
    | '/'
    | '/business'
    | '/console'
    | '/shop'
    | '/health'
    | '/live'
    | '/shop/$slug'
    | '/console/onboarding'
    | '/q/$shortCode'
    | '/business/'
    | '/console/'
    | '/shop/'
    | '/api/menu-import/upload'
    | '/api/mollie/callback'
    | '/console/menu/import'
    | '/console/settings/merchant'
    | '/console/settings/payments'
    | '/console/settings/subscription'
    | '/console/stores/$storeId'
    | '/console/stores/new'
    | '/console/menu/'
    | '/console/settings/'
    | '/console/stores/'
    | '/shop/$slug/'
    | '/console/menu/items/$itemId'
    | '/console/menu/items/new'
    | '/shop/$slug/checkout/return'
    | '/shop/$slug/order/$orderId'
    | '/shop/$slug/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRouteRoute: typeof BusinessRouteRouteWithChildren
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  ShopRouteRoute: typeof ShopRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  LiveRoute: typeof LiveRoute
  QShortCodeRoute: typeof QShortCodeRoute
  ApiMenuImportUploadRoute: typeof ApiMenuImportUploadRoute
  ApiMollieCallbackRoute: typeof ApiMollieCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRouteRoute
    }
    '/q/$shortCode': {
      id: '/q/$shortCode'
      path: '/q/$shortCode'
      fullPath: '/q/$shortCode'
      preLoaderRoute: typeof QShortCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/onboarding': {
      id: '/console/onboarding'
      path: '/onboarding'
      fullPath: '/console/onboarding'
      preLoaderRoute: typeof ConsoleOnboardingRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/shop/$slug/': {
      id: '/shop/$slug/'
      path: '/'
      fullPath: '/shop/$slug/'
      preLoaderRoute: typeof ShopSlugIndexRouteImport
      parentRoute: typeof ShopSlugRouteRoute
    }
    '/console/stores/': {
      id: '/console/stores/'
      path: '/stores'
      fullPath: '/console/stores'
      preLoaderRoute: typeof ConsoleStoresIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/settings/': {
      id: '/console/settings/'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ConsoleSettingsIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/menu/': {
      id: '/console/menu/'
      path: '/menu'
      fullPath: '/console/menu'
      preLoaderRoute: typeof ConsoleMenuIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/stores/new': {
      id: '/console/stores/new'
      path: '/stores/new'
      fullPath: '/console/stores/new'
      preLoaderRoute: typeof ConsoleStoresNewRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/stores/$storeId': {
      id: '/console/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/console/stores/$storeId'
      preLoaderRoute: typeof ConsoleStoresStoreIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/settings/subscription': {
      id: '/console/settings/subscription'
      path: '/settings/subscription'
      fullPath: '/console/settings/subscription'
      preLoaderRoute: typeof ConsoleSettingsSubscriptionRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/settings/payments': {
      id: '/console/settings/payments'
      path: '/settings/payments'
      fullPath: '/console/settings/payments'
      preLoaderRoute: typeof ConsoleSettingsPaymentsRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/settings/merchant': {
      id: '/console/settings/merchant'
      path: '/settings/merchant'
      fullPath: '/console/settings/merchant'
      preLoaderRoute: typeof ConsoleSettingsMerchantRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/menu/import': {
      id: '/console/menu/import'
      path: '/menu/import'
      fullPath: '/console/menu/import'
      preLoaderRoute: typeof ConsoleMenuImportRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/api/mollie/callback': {
      id: '/api/mollie/callback'
      path: '/api/mollie/callback'
      fullPath: '/api/mollie/callback'
      preLoaderRoute: typeof ApiMollieCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/menu-import/upload': {
      id: '/api/menu-import/upload'
      path: '/api/menu-import/upload'
      fullPath: '/api/menu-import/upload'
      preLoaderRoute: typeof ApiMenuImportUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug/checkout/': {
      id: '/shop/$slug/checkout/'
      path: '/checkout'
      fullPath: '/shop/$slug/checkout'
      preLoaderRoute: typeof ShopSlugCheckoutIndexRouteImport
      parentRoute: typeof ShopSlugRouteRoute
    }
    '/shop/$slug/order/$orderId': {
      id: '/shop/$slug/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/shop/$slug/order/$orderId'
      preLoaderRoute: typeof ShopSlugOrderOrderIdRouteImport
      parentRoute: typeof ShopSlugRouteRoute
    }
    '/shop/$slug/checkout/return': {
      id: '/shop/$slug/checkout/return'
      path: '/checkout/return'
      fullPath: '/shop/$slug/checkout/return'
      preLoaderRoute: typeof ShopSlugCheckoutReturnRouteImport
      parentRoute: typeof ShopSlugRouteRoute
    }
    '/console/menu/items/new': {
      id: '/console/menu/items/new'
      path: '/menu/items/new'
      fullPath: '/console/menu/items/new'
      preLoaderRoute: typeof ConsoleMenuItemsNewRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/menu/items/$itemId': {
      id: '/console/menu/items/$itemId'
      path: '/menu/items/$itemId'
      fullPath: '/console/menu/items/$itemId'
      preLoaderRoute: typeof ConsoleMenuItemsItemIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
  }
}

interface BusinessRouteRouteChildren {
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteRouteChildren: BusinessRouteRouteChildren = {
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteRouteWithChildren = BusinessRouteRoute._addFileChildren(
  BusinessRouteRouteChildren,
)

interface ConsoleRouteRouteChildren {
  ConsoleOnboardingRoute: typeof ConsoleOnboardingRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleMenuImportRoute: typeof ConsoleMenuImportRoute
  ConsoleSettingsMerchantRoute: typeof ConsoleSettingsMerchantRoute
  ConsoleSettingsPaymentsRoute: typeof ConsoleSettingsPaymentsRoute
  ConsoleSettingsSubscriptionRoute: typeof ConsoleSettingsSubscriptionRoute
  ConsoleStoresStoreIdRoute: typeof ConsoleStoresStoreIdRoute
  ConsoleStoresNewRoute: typeof ConsoleStoresNewRoute
  ConsoleMenuIndexRoute: typeof ConsoleMenuIndexRoute
  ConsoleSettingsIndexRoute: typeof ConsoleSettingsIndexRoute
  ConsoleStoresIndexRoute: typeof ConsoleStoresIndexRoute
  ConsoleMenuItemsItemIdRoute: typeof ConsoleMenuItemsItemIdRoute
  ConsoleMenuItemsNewRoute: typeof ConsoleMenuItemsNewRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleOnboardingRoute: ConsoleOnboardingRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleMenuImportRoute: ConsoleMenuImportRoute,
  ConsoleSettingsMerchantRoute: ConsoleSettingsMerchantRoute,
  ConsoleSettingsPaymentsRoute: ConsoleSettingsPaymentsRoute,
  ConsoleSettingsSubscriptionRoute: ConsoleSettingsSubscriptionRoute,
  ConsoleStoresStoreIdRoute: ConsoleStoresStoreIdRoute,
  ConsoleStoresNewRoute: ConsoleStoresNewRoute,
  ConsoleMenuIndexRoute: ConsoleMenuIndexRoute,
  ConsoleSettingsIndexRoute: ConsoleSettingsIndexRoute,
  ConsoleStoresIndexRoute: ConsoleStoresIndexRoute,
  ConsoleMenuItemsItemIdRoute: ConsoleMenuItemsItemIdRoute,
  ConsoleMenuItemsNewRoute: ConsoleMenuItemsNewRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

interface ShopSlugRouteRouteChildren {
  ShopSlugIndexRoute: typeof ShopSlugIndexRoute
  ShopSlugCheckoutReturnRoute: typeof ShopSlugCheckoutReturnRoute
  ShopSlugOrderOrderIdRoute: typeof ShopSlugOrderOrderIdRoute
  ShopSlugCheckoutIndexRoute: typeof ShopSlugCheckoutIndexRoute
}

const ShopSlugRouteRouteChildren: ShopSlugRouteRouteChildren = {
  ShopSlugIndexRoute: ShopSlugIndexRoute,
  ShopSlugCheckoutReturnRoute: ShopSlugCheckoutReturnRoute,
  ShopSlugOrderOrderIdRoute: ShopSlugOrderOrderIdRoute,
  ShopSlugCheckoutIndexRoute: ShopSlugCheckoutIndexRoute,
}

const ShopSlugRouteRouteWithChildren = ShopSlugRouteRoute._addFileChildren(
  ShopSlugRouteRouteChildren,
)

interface ShopRouteRouteChildren {
  ShopSlugRouteRoute: typeof ShopSlugRouteRouteWithChildren
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteRouteChildren: ShopRouteRouteChildren = {
  ShopSlugRouteRoute: ShopSlugRouteRouteWithChildren,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteRouteWithChildren = ShopRouteRoute._addFileChildren(
  ShopRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRouteRoute: BusinessRouteRouteWithChildren,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  ShopRouteRoute: ShopRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  LiveRoute: LiveRoute,
  QShortCodeRoute: QShortCodeRoute,
  ApiMenuImportUploadRoute: ApiMenuImportUploadRoute,
  ApiMollieCallbackRoute: ApiMollieCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
