/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ShopRouteRouteImport } from './routes/shop/route'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'
import { Route as ConsoleStoresIndexRouteImport } from './routes/console/stores/index'
import { Route as ConsoleSettingsIndexRouteImport } from './routes/console/settings/index'
import { Route as ConsoleMenuIndexRouteImport } from './routes/console/menu/index'
import { Route as ConsoleStoresNewRouteImport } from './routes/console/stores/new'
import { Route as ConsoleStoresStoreIdRouteImport } from './routes/console/stores/$storeId'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api.webhooks.stripe'
import { Route as ApiImagesUploadRouteImport } from './routes/api.images.upload'
import { Route as ConsoleSettingsStoresStoreIdRouteImport } from './routes/console/settings/stores.$storeId'
import { Route as ConsoleMenuItemsNewRouteImport } from './routes/console/menu/items/new'
import { Route as ConsoleMenuItemsItemIdRouteImport } from './routes/console/menu/items/$itemId'
import { Route as ConsoleMenuCategoriesCategoryIdRouteImport } from './routes/console/menu/categories/$categoryId'
import { Route as ApiWebhooksStripeThinRouteImport } from './routes/api.webhooks.stripe.thin'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRouteRoute = ShopRouteRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRouteRoute,
} as any)
const ConsoleStoresIndexRoute = ConsoleStoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSettingsIndexRoute = ConsoleSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleMenuIndexRoute = ConsoleMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleStoresNewRoute = ConsoleStoresNewRouteImport.update({
  id: '/stores/new',
  path: '/stores/new',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleStoresStoreIdRoute = ConsoleStoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesUploadRoute = ApiImagesUploadRouteImport.update({
  id: '/api/images/upload',
  path: '/api/images/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleSettingsStoresStoreIdRoute =
  ConsoleSettingsStoresStoreIdRouteImport.update({
    id: '/settings/stores/$storeId',
    path: '/settings/stores/$storeId',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleMenuItemsNewRoute = ConsoleMenuItemsNewRouteImport.update({
  id: '/menu/items/new',
  path: '/menu/items/new',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleMenuItemsItemIdRoute = ConsoleMenuItemsItemIdRouteImport.update({
  id: '/menu/items/$itemId',
  path: '/menu/items/$itemId',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleMenuCategoriesCategoryIdRoute =
  ConsoleMenuCategoriesCategoryIdRouteImport.update({
    id: '/menu/categories/$categoryId',
    path: '/menu/categories/$categoryId',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ApiWebhooksStripeThinRoute = ApiWebhooksStripeThinRouteImport.update({
  id: '/thin',
  path: '/thin',
  getParentRoute: () => ApiWebhooksStripeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/shop': typeof ShopRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/console/': typeof ConsoleIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/images/upload': typeof ApiImagesUploadRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRouteWithChildren
  '/console/stores/$storeId': typeof ConsoleStoresStoreIdRoute
  '/console/stores/new': typeof ConsoleStoresNewRoute
  '/console/menu': typeof ConsoleMenuIndexRoute
  '/console/settings': typeof ConsoleSettingsIndexRoute
  '/console/stores': typeof ConsoleStoresIndexRoute
  '/api/webhooks/stripe/thin': typeof ApiWebhooksStripeThinRoute
  '/console/menu/categories/$categoryId': typeof ConsoleMenuCategoriesCategoryIdRoute
  '/console/menu/items/$itemId': typeof ConsoleMenuItemsItemIdRoute
  '/console/menu/items/new': typeof ConsoleMenuItemsNewRoute
  '/console/settings/stores/$storeId': typeof ConsoleSettingsStoresStoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/console': typeof ConsoleIndexRoute
  '/shop': typeof ShopIndexRoute
  '/api/images/upload': typeof ApiImagesUploadRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRouteWithChildren
  '/console/stores/$storeId': typeof ConsoleStoresStoreIdRoute
  '/console/stores/new': typeof ConsoleStoresNewRoute
  '/console/menu': typeof ConsoleMenuIndexRoute
  '/console/settings': typeof ConsoleSettingsIndexRoute
  '/console/stores': typeof ConsoleStoresIndexRoute
  '/api/webhooks/stripe/thin': typeof ApiWebhooksStripeThinRoute
  '/console/menu/categories/$categoryId': typeof ConsoleMenuCategoriesCategoryIdRoute
  '/console/menu/items/$itemId': typeof ConsoleMenuItemsItemIdRoute
  '/console/menu/items/new': typeof ConsoleMenuItemsNewRoute
  '/console/settings/stores/$storeId': typeof ConsoleSettingsStoresStoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/shop': typeof ShopRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/console/': typeof ConsoleIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/images/upload': typeof ApiImagesUploadRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRouteWithChildren
  '/console/stores/$storeId': typeof ConsoleStoresStoreIdRoute
  '/console/stores/new': typeof ConsoleStoresNewRoute
  '/console/menu/': typeof ConsoleMenuIndexRoute
  '/console/settings/': typeof ConsoleSettingsIndexRoute
  '/console/stores/': typeof ConsoleStoresIndexRoute
  '/api/webhooks/stripe/thin': typeof ApiWebhooksStripeThinRoute
  '/console/menu/categories/$categoryId': typeof ConsoleMenuCategoriesCategoryIdRoute
  '/console/menu/items/$itemId': typeof ConsoleMenuItemsItemIdRoute
  '/console/menu/items/new': typeof ConsoleMenuItemsNewRoute
  '/console/settings/stores/$storeId': typeof ConsoleSettingsStoresStoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/shop'
    | '/onboarding'
    | '/shop/$slug'
    | '/console/'
    | '/shop/'
    | '/api/images/upload'
    | '/api/webhooks/stripe'
    | '/console/stores/$storeId'
    | '/console/stores/new'
    | '/console/menu'
    | '/console/settings'
    | '/console/stores'
    | '/api/webhooks/stripe/thin'
    | '/console/menu/categories/$categoryId'
    | '/console/menu/items/$itemId'
    | '/console/menu/items/new'
    | '/console/settings/stores/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/shop/$slug'
    | '/console'
    | '/shop'
    | '/api/images/upload'
    | '/api/webhooks/stripe'
    | '/console/stores/$storeId'
    | '/console/stores/new'
    | '/console/menu'
    | '/console/settings'
    | '/console/stores'
    | '/api/webhooks/stripe/thin'
    | '/console/menu/categories/$categoryId'
    | '/console/menu/items/$itemId'
    | '/console/menu/items/new'
    | '/console/settings/stores/$storeId'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/shop'
    | '/onboarding'
    | '/shop/$slug'
    | '/console/'
    | '/shop/'
    | '/api/images/upload'
    | '/api/webhooks/stripe'
    | '/console/stores/$storeId'
    | '/console/stores/new'
    | '/console/menu/'
    | '/console/settings/'
    | '/console/stores/'
    | '/api/webhooks/stripe/thin'
    | '/console/menu/categories/$categoryId'
    | '/console/menu/items/$itemId'
    | '/console/menu/items/new'
    | '/console/settings/stores/$storeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  ShopRouteRoute: typeof ShopRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ApiImagesUploadRoute: typeof ApiImagesUploadRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRouteRoute
    }
    '/console/stores/': {
      id: '/console/stores/'
      path: '/stores'
      fullPath: '/console/stores'
      preLoaderRoute: typeof ConsoleStoresIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/settings/': {
      id: '/console/settings/'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ConsoleSettingsIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/menu/': {
      id: '/console/menu/'
      path: '/menu'
      fullPath: '/console/menu'
      preLoaderRoute: typeof ConsoleMenuIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/stores/new': {
      id: '/console/stores/new'
      path: '/stores/new'
      fullPath: '/console/stores/new'
      preLoaderRoute: typeof ConsoleStoresNewRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/stores/$storeId': {
      id: '/console/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/console/stores/$storeId'
      preLoaderRoute: typeof ConsoleStoresStoreIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/upload': {
      id: '/api/images/upload'
      path: '/api/images/upload'
      fullPath: '/api/images/upload'
      preLoaderRoute: typeof ApiImagesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/settings/stores/$storeId': {
      id: '/console/settings/stores/$storeId'
      path: '/settings/stores/$storeId'
      fullPath: '/console/settings/stores/$storeId'
      preLoaderRoute: typeof ConsoleSettingsStoresStoreIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/menu/items/new': {
      id: '/console/menu/items/new'
      path: '/menu/items/new'
      fullPath: '/console/menu/items/new'
      preLoaderRoute: typeof ConsoleMenuItemsNewRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/menu/items/$itemId': {
      id: '/console/menu/items/$itemId'
      path: '/menu/items/$itemId'
      fullPath: '/console/menu/items/$itemId'
      preLoaderRoute: typeof ConsoleMenuItemsItemIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/menu/categories/$categoryId': {
      id: '/console/menu/categories/$categoryId'
      path: '/menu/categories/$categoryId'
      fullPath: '/console/menu/categories/$categoryId'
      preLoaderRoute: typeof ConsoleMenuCategoriesCategoryIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/api/webhooks/stripe/thin': {
      id: '/api/webhooks/stripe/thin'
      path: '/thin'
      fullPath: '/api/webhooks/stripe/thin'
      preLoaderRoute: typeof ApiWebhooksStripeThinRouteImport
      parentRoute: typeof ApiWebhooksStripeRoute
    }
  }
}

interface ConsoleRouteRouteChildren {
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleStoresStoreIdRoute: typeof ConsoleStoresStoreIdRoute
  ConsoleStoresNewRoute: typeof ConsoleStoresNewRoute
  ConsoleMenuIndexRoute: typeof ConsoleMenuIndexRoute
  ConsoleSettingsIndexRoute: typeof ConsoleSettingsIndexRoute
  ConsoleStoresIndexRoute: typeof ConsoleStoresIndexRoute
  ConsoleMenuCategoriesCategoryIdRoute: typeof ConsoleMenuCategoriesCategoryIdRoute
  ConsoleMenuItemsItemIdRoute: typeof ConsoleMenuItemsItemIdRoute
  ConsoleMenuItemsNewRoute: typeof ConsoleMenuItemsNewRoute
  ConsoleSettingsStoresStoreIdRoute: typeof ConsoleSettingsStoresStoreIdRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleStoresStoreIdRoute: ConsoleStoresStoreIdRoute,
  ConsoleStoresNewRoute: ConsoleStoresNewRoute,
  ConsoleMenuIndexRoute: ConsoleMenuIndexRoute,
  ConsoleSettingsIndexRoute: ConsoleSettingsIndexRoute,
  ConsoleStoresIndexRoute: ConsoleStoresIndexRoute,
  ConsoleMenuCategoriesCategoryIdRoute: ConsoleMenuCategoriesCategoryIdRoute,
  ConsoleMenuItemsItemIdRoute: ConsoleMenuItemsItemIdRoute,
  ConsoleMenuItemsNewRoute: ConsoleMenuItemsNewRoute,
  ConsoleSettingsStoresStoreIdRoute: ConsoleSettingsStoresStoreIdRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

interface ShopRouteRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteRouteChildren: ShopRouteRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteRouteWithChildren = ShopRouteRoute._addFileChildren(
  ShopRouteRouteChildren,
)

interface ApiWebhooksStripeRouteChildren {
  ApiWebhooksStripeThinRoute: typeof ApiWebhooksStripeThinRoute
}

const ApiWebhooksStripeRouteChildren: ApiWebhooksStripeRouteChildren = {
  ApiWebhooksStripeThinRoute: ApiWebhooksStripeThinRoute,
}

const ApiWebhooksStripeRouteWithChildren =
  ApiWebhooksStripeRoute._addFileChildren(ApiWebhooksStripeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  ShopRouteRoute: ShopRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ApiImagesUploadRoute: ApiImagesUploadRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
