/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RouteRouteImport } from './routes/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresIndexRouteImport } from './routes/stores/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as MenuIndexRouteImport } from './routes/menu/index'
import { Route as KitchenIndexRouteImport } from './routes/kitchen/index'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as StoresNewRouteImport } from './routes/stores/new'
import { Route as StoresStoreIdRouteImport } from './routes/stores/$storeId'
import { Route as SettingsSubscriptionRouteImport } from './routes/settings/subscription'
import { Route as SettingsPaymentsRouteImport } from './routes/settings/payments'
import { Route as SettingsMerchantRouteImport } from './routes/settings/merchant'
import { Route as MenuImportRouteImport } from './routes/menu/import'
import { Route as MenuOptionsIndexRouteImport } from './routes/menu/options/index'
import { Route as MenuOptionsNewRouteImport } from './routes/menu/options/new'
import { Route as MenuOptionsOptionGroupIdRouteImport } from './routes/menu/options/$optionGroupId'
import { Route as MenuCategoriesNewRouteImport } from './routes/menu/categories/new'
import { Route as MenuCategoriesCategoryIdIndexRouteImport } from './routes/menu/categories/$categoryId/index'
import { Route as MenuCategoriesCategoryIdEditRouteImport } from './routes/menu/categories/$categoryId/edit'
import { Route as MenuCategoriesCategoryIdItemsNewRouteImport } from './routes/menu/categories/$categoryId/items/new'
import { Route as MenuCategoriesCategoryIdItemsItemIdRouteImport } from './routes/menu/categories/$categoryId/items/$itemId'

const RouteRoute = RouteRouteImport.update({
  id: '',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenIndexRoute = KitchenIndexRouteImport.update({
  id: '/kitchen/',
  path: '/kitchen/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresNewRoute = StoresNewRouteImport.update({
  id: '/stores/new',
  path: '/stores/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSubscriptionRoute = SettingsSubscriptionRouteImport.update({
  id: '/settings/subscription',
  path: '/settings/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPaymentsRoute = SettingsPaymentsRouteImport.update({
  id: '/settings/payments',
  path: '/settings/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMerchantRoute = SettingsMerchantRouteImport.update({
  id: '/settings/merchant',
  path: '/settings/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuImportRoute = MenuImportRouteImport.update({
  id: '/menu/import',
  path: '/menu/import',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuOptionsIndexRoute = MenuOptionsIndexRouteImport.update({
  id: '/menu/options/',
  path: '/menu/options/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuOptionsNewRoute = MenuOptionsNewRouteImport.update({
  id: '/menu/options/new',
  path: '/menu/options/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuOptionsOptionGroupIdRoute =
  MenuOptionsOptionGroupIdRouteImport.update({
    id: '/menu/options/$optionGroupId',
    path: '/menu/options/$optionGroupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MenuCategoriesNewRoute = MenuCategoriesNewRouteImport.update({
  id: '/menu/categories/new',
  path: '/menu/categories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuCategoriesCategoryIdIndexRoute =
  MenuCategoriesCategoryIdIndexRouteImport.update({
    id: '/menu/categories/$categoryId/',
    path: '/menu/categories/$categoryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MenuCategoriesCategoryIdEditRoute =
  MenuCategoriesCategoryIdEditRouteImport.update({
    id: '/menu/categories/$categoryId/edit',
    path: '/menu/categories/$categoryId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const MenuCategoriesCategoryIdItemsNewRoute =
  MenuCategoriesCategoryIdItemsNewRouteImport.update({
    id: '/menu/categories/$categoryId/items/new',
    path: '/menu/categories/$categoryId/items/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const MenuCategoriesCategoryIdItemsItemIdRoute =
  MenuCategoriesCategoryIdItemsItemIdRouteImport.update({
    id: '/menu/categories/$categoryId/items/$itemId',
    path: '/menu/categories/$categoryId/items/$itemId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu/import': typeof MenuImportRoute
  '/settings/merchant': typeof SettingsMerchantRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores/new': typeof StoresNewRoute
  '/help': typeof HelpIndexRoute
  '/kitchen': typeof KitchenIndexRoute
  '/menu': typeof MenuIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/stores': typeof StoresIndexRoute
  '/menu/categories/new': typeof MenuCategoriesNewRoute
  '/menu/options/$optionGroupId': typeof MenuOptionsOptionGroupIdRoute
  '/menu/options/new': typeof MenuOptionsNewRoute
  '/menu/options': typeof MenuOptionsIndexRoute
  '/menu/categories/$categoryId/edit': typeof MenuCategoriesCategoryIdEditRoute
  '/menu/categories/$categoryId': typeof MenuCategoriesCategoryIdIndexRoute
  '/menu/categories/$categoryId/items/$itemId': typeof MenuCategoriesCategoryIdItemsItemIdRoute
  '/menu/categories/$categoryId/items/new': typeof MenuCategoriesCategoryIdItemsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu/import': typeof MenuImportRoute
  '/settings/merchant': typeof SettingsMerchantRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores/new': typeof StoresNewRoute
  '/help': typeof HelpIndexRoute
  '/kitchen': typeof KitchenIndexRoute
  '/menu': typeof MenuIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/stores': typeof StoresIndexRoute
  '/menu/categories/new': typeof MenuCategoriesNewRoute
  '/menu/options/$optionGroupId': typeof MenuOptionsOptionGroupIdRoute
  '/menu/options/new': typeof MenuOptionsNewRoute
  '/menu/options': typeof MenuOptionsIndexRoute
  '/menu/categories/$categoryId/edit': typeof MenuCategoriesCategoryIdEditRoute
  '/menu/categories/$categoryId': typeof MenuCategoriesCategoryIdIndexRoute
  '/menu/categories/$categoryId/items/$itemId': typeof MenuCategoriesCategoryIdItemsItemIdRoute
  '/menu/categories/$categoryId/items/new': typeof MenuCategoriesCategoryIdItemsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '': typeof RouteRoute
  '/menu/import': typeof MenuImportRoute
  '/settings/merchant': typeof SettingsMerchantRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores/new': typeof StoresNewRoute
  '/help/': typeof HelpIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/menu/categories/new': typeof MenuCategoriesNewRoute
  '/menu/options/$optionGroupId': typeof MenuOptionsOptionGroupIdRoute
  '/menu/options/new': typeof MenuOptionsNewRoute
  '/menu/options/': typeof MenuOptionsIndexRoute
  '/menu/categories/$categoryId/edit': typeof MenuCategoriesCategoryIdEditRoute
  '/menu/categories/$categoryId/': typeof MenuCategoriesCategoryIdIndexRoute
  '/menu/categories/$categoryId/items/$itemId': typeof MenuCategoriesCategoryIdItemsItemIdRoute
  '/menu/categories/$categoryId/items/new': typeof MenuCategoriesCategoryIdItemsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/menu/import'
    | '/settings/merchant'
    | '/settings/payments'
    | '/settings/subscription'
    | '/stores/$storeId'
    | '/stores/new'
    | '/help'
    | '/kitchen'
    | '/menu'
    | '/orders'
    | '/settings'
    | '/stores'
    | '/menu/categories/new'
    | '/menu/options/$optionGroupId'
    | '/menu/options/new'
    | '/menu/options'
    | '/menu/categories/$categoryId/edit'
    | '/menu/categories/$categoryId'
    | '/menu/categories/$categoryId/items/$itemId'
    | '/menu/categories/$categoryId/items/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/menu/import'
    | '/settings/merchant'
    | '/settings/payments'
    | '/settings/subscription'
    | '/stores/$storeId'
    | '/stores/new'
    | '/help'
    | '/kitchen'
    | '/menu'
    | '/orders'
    | '/settings'
    | '/stores'
    | '/menu/categories/new'
    | '/menu/options/$optionGroupId'
    | '/menu/options/new'
    | '/menu/options'
    | '/menu/categories/$categoryId/edit'
    | '/menu/categories/$categoryId'
    | '/menu/categories/$categoryId/items/$itemId'
    | '/menu/categories/$categoryId/items/new'
  id:
    | '__root__'
    | '/'
    | ''
    | '/menu/import'
    | '/settings/merchant'
    | '/settings/payments'
    | '/settings/subscription'
    | '/stores/$storeId'
    | '/stores/new'
    | '/help/'
    | '/kitchen/'
    | '/menu/'
    | '/orders/'
    | '/settings/'
    | '/stores/'
    | '/menu/categories/new'
    | '/menu/options/$optionGroupId'
    | '/menu/options/new'
    | '/menu/options/'
    | '/menu/categories/$categoryId/edit'
    | '/menu/categories/$categoryId/'
    | '/menu/categories/$categoryId/items/$itemId'
    | '/menu/categories/$categoryId/items/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RouteRoute: typeof RouteRoute
  MenuImportRoute: typeof MenuImportRoute
  SettingsMerchantRoute: typeof SettingsMerchantRoute
  SettingsPaymentsRoute: typeof SettingsPaymentsRoute
  SettingsSubscriptionRoute: typeof SettingsSubscriptionRoute
  StoresStoreIdRoute: typeof StoresStoreIdRoute
  StoresNewRoute: typeof StoresNewRoute
  HelpIndexRoute: typeof HelpIndexRoute
  KitchenIndexRoute: typeof KitchenIndexRoute
  MenuIndexRoute: typeof MenuIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
  MenuCategoriesNewRoute: typeof MenuCategoriesNewRoute
  MenuOptionsOptionGroupIdRoute: typeof MenuOptionsOptionGroupIdRoute
  MenuOptionsNewRoute: typeof MenuOptionsNewRoute
  MenuOptionsIndexRoute: typeof MenuOptionsIndexRoute
  MenuCategoriesCategoryIdEditRoute: typeof MenuCategoriesCategoryIdEditRoute
  MenuCategoriesCategoryIdIndexRoute: typeof MenuCategoriesCategoryIdIndexRoute
  MenuCategoriesCategoryIdItemsItemIdRoute: typeof MenuCategoriesCategoryIdItemsItemIdRoute
  MenuCategoriesCategoryIdItemsNewRoute: typeof MenuCategoriesCategoryIdItemsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '': {
      id: ''
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen/': {
      id: '/kitchen/'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/new': {
      id: '/stores/new'
      path: '/stores/new'
      fullPath: '/stores/new'
      preLoaderRoute: typeof StoresNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/subscription': {
      id: '/settings/subscription'
      path: '/settings/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof SettingsSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/payments': {
      id: '/settings/payments'
      path: '/settings/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof SettingsPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/merchant': {
      id: '/settings/merchant'
      path: '/settings/merchant'
      fullPath: '/settings/merchant'
      preLoaderRoute: typeof SettingsMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/import': {
      id: '/menu/import'
      path: '/menu/import'
      fullPath: '/menu/import'
      preLoaderRoute: typeof MenuImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/options/': {
      id: '/menu/options/'
      path: '/menu/options'
      fullPath: '/menu/options'
      preLoaderRoute: typeof MenuOptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/options/new': {
      id: '/menu/options/new'
      path: '/menu/options/new'
      fullPath: '/menu/options/new'
      preLoaderRoute: typeof MenuOptionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/options/$optionGroupId': {
      id: '/menu/options/$optionGroupId'
      path: '/menu/options/$optionGroupId'
      fullPath: '/menu/options/$optionGroupId'
      preLoaderRoute: typeof MenuOptionsOptionGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/categories/new': {
      id: '/menu/categories/new'
      path: '/menu/categories/new'
      fullPath: '/menu/categories/new'
      preLoaderRoute: typeof MenuCategoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/categories/$categoryId/': {
      id: '/menu/categories/$categoryId/'
      path: '/menu/categories/$categoryId'
      fullPath: '/menu/categories/$categoryId'
      preLoaderRoute: typeof MenuCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/categories/$categoryId/edit': {
      id: '/menu/categories/$categoryId/edit'
      path: '/menu/categories/$categoryId/edit'
      fullPath: '/menu/categories/$categoryId/edit'
      preLoaderRoute: typeof MenuCategoriesCategoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/categories/$categoryId/items/new': {
      id: '/menu/categories/$categoryId/items/new'
      path: '/menu/categories/$categoryId/items/new'
      fullPath: '/menu/categories/$categoryId/items/new'
      preLoaderRoute: typeof MenuCategoriesCategoryIdItemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/categories/$categoryId/items/$itemId': {
      id: '/menu/categories/$categoryId/items/$itemId'
      path: '/menu/categories/$categoryId/items/$itemId'
      fullPath: '/menu/categories/$categoryId/items/$itemId'
      preLoaderRoute: typeof MenuCategoriesCategoryIdItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RouteRoute: RouteRoute,
  MenuImportRoute: MenuImportRoute,
  SettingsMerchantRoute: SettingsMerchantRoute,
  SettingsPaymentsRoute: SettingsPaymentsRoute,
  SettingsSubscriptionRoute: SettingsSubscriptionRoute,
  StoresStoreIdRoute: StoresStoreIdRoute,
  StoresNewRoute: StoresNewRoute,
  HelpIndexRoute: HelpIndexRoute,
  KitchenIndexRoute: KitchenIndexRoute,
  MenuIndexRoute: MenuIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
  MenuCategoriesNewRoute: MenuCategoriesNewRoute,
  MenuOptionsOptionGroupIdRoute: MenuOptionsOptionGroupIdRoute,
  MenuOptionsNewRoute: MenuOptionsNewRoute,
  MenuOptionsIndexRoute: MenuOptionsIndexRoute,
  MenuCategoriesCategoryIdEditRoute: MenuCategoriesCategoryIdEditRoute,
  MenuCategoriesCategoryIdIndexRoute: MenuCategoriesCategoryIdIndexRoute,
  MenuCategoriesCategoryIdItemsItemIdRoute:
    MenuCategoriesCategoryIdItemsItemIdRoute,
  MenuCategoriesCategoryIdItemsNewRoute: MenuCategoriesCategoryIdItemsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
